(function(k){var n=window.AmazonUIPageJS||window.P,p=n._namespace||n.attributeErrors,l=p?p("DigitalVideoLoggingAssets"):n;l.guardFatal?l.guardFatal(k)(l,window):l.execute(function(){k(l,window)})})(function(k,n,p){k.when("jQuery","dv-utils-stringify").register("logging",function(l,v){var p=function(c){var b=n.console;return b&&b[c]&&"function"===typeof b[c]?b[c]:function(){}},d={fatal:{consoleMethod:"error",logLevel:0,errorLevel:"FATAL"},error:{consoleMethod:"error",logLevel:1,errorLevel:"ERROR"},
warn:{consoleMethod:"warn",logLevel:2,errorLevel:"WARNING"},info:{consoleMethod:"info",logLevel:3,errorLevel:null},debug:{consoleMethod:"debug",logLevel:4,errorLevel:null},log:{consoleMethod:"log",logLevel:4,errorLevel:null},trace:{consoleMethod:"trace",logLevel:5,errorLevel:null}},h={},a;for(a in d)d.hasOwnProperty(a)&&(h[d[a].consoleMethod]=p(d[a].consoleMethod));var f=function(c){c=c||null;var b,r,e="";try{b=f.caller&&f.caller.caller&&f.caller.caller.caller||{},r=b.name||b._name||null}catch(a){}c&&
(e+=c.charAt(0).toUpperCase()+c.slice(1));r&&(e+=":"+r);return e},t=function(){var c=!1,b=/\baivDebug=1\b/;if(document.cookie.match(b)||document.location.search.match(b))c=!0;return c}(),w=function(){var c=!1,b=/\baivEmulateConsole=1\b/;if(document.cookie.match(b)||document.location.search.match(b))c=!0;return c}(),q;q=w?l("\x3cul /\x3e").addClass("dv-emulated-console").appendTo("body"):void 0;var x={},u=function(c,b){this._scriptName=c||null;this._log=b&&b.log?function(c,e,a){b.log(c,e,a)}:k.log?
function(c,b,a){k.log(c,b,a)}:function(c,b){n.ueLogError(null,{logLevel:b,message:c})}};for(a in d)d.hasOwnProperty(a)&&function(c){u.prototype[c]=function(){var b=d[c].consoleMethod,a=arguments,e=d[c].logLevel,g=d[c].errorLevel,m="string"===typeof this._scriptName?this._scriptName.toLowerCase():null,a=Array.prototype.slice.call(a),k="";((e=h&&h[b]&&"function"===typeof h[b]&&(t||m&&x[m])&&6>=e&&a)||g)&&(k=f(this._scriptName))&&a.unshift("["+k+"]");if(e&&(h[b].apply(n.console,a),w)){e=[];for(m=0;m<
a.length;m++)"object"===typeof a[m]?e.push(v(a[m])):e.push(a[m]);l("\x3cli /\x3e").text(e.join(" ")).addClass("dv-console-"+b).appendTo(q);q.scrollTop(q.get(0).scrollHeight)}g&&this._log&&this._log(v(a),g,k)}}(a);var g={create:function(a,b){g._mockConsole&&"object"===typeof g._mockConsole&&(h=g._mockConsole);g._mockDebugFlag&&"boolean"===typeof g._mockDebugFlag&&(t=g._mockDebugFlag);return new u(a,b)},extend:function(a,b,d){g._mockConsole&&"object"===typeof g._mockConsole&&(h=g._mockConsole);g._mockDebugFlag&&
"boolean"===typeof g._mockDebugFlag&&(t=g._mockDebugFlag);var e=a.prototype||a;b=new u(b,d);l.extend(e,b);for(var f in e)e.hasOwnProperty(f)&&"function"===typeof e[f]&&(e[f]._name=e[f].name||f);return a}};for(a in d)d.hasOwnProperty(a)&&(g[a]=function(){var c=a,b=arguments,d=g.create();d[c].apply(d,b)});return g});k.register("dv-utils-stringify",function(){return function(l){var k=[];return"object"===typeof JSON&&"function"===typeof JSON.stringify?JSON.stringify(l,function(l,d){if("object"===typeof d&&
null!==d){if(-1!==k.indexOf(d))return;k.push(d)}return d}):function d(h){var a;switch(h.constructor){case Object:a=[];for(var f in h)if(h.hasOwnProperty(f)&&-1===k.indexOf(h[f])){k.push(h[f]);var l=d(h[f]);l&&a.push('"'+f+'":'+l)}a="{"+a.join(",")+"}";break;case Array:a=[];for(f=0;f<h.length;++f)a.push(d(h[f]));a="["+a.join(",")+"]";break;case String:a='"'+h.toString()+'"';break;case Function:break;default:a=h.toString()}return a}(l)}})});
/* ******** */
(function(k){var u=window.AmazonUIPageJS||window.P,A=u._namespace||u.attributeErrors,e=A?A("DigitalVideoWebUtilityAssets"):u;e.guardFatal?e.guardFatal(k)(e,window):e.execute(function(){k(e,window)})})(function(k,u,A){k.when("jQuery","logging","dv-alert-templates-ready").register("aiv-alerts",function(e,b){function d(b,c,a,f){"undefined"===typeof c&&(c="inline");"undefined"===typeof f&&(f="info");c=["dv-alert-template",c,f].join("-");f=e("#"+c).html();g.debug("getAlert",c,f);"light"===a&&f&&(f=f.replace(/dv-alerts-dark/g,
"dv-alerts-light"));return l(e(f),b)}function l(b,c){if(0===b.length)g.error("_addContent missing $template",arguments);else{if(c)return b.find(".a-alert-content").html(c).end()[0].outerHTML;g.error("_addContent missing content",arguments)}}var g=b.create("aiv-alerts");return{getAlert:d,info:function(b,c,a){return d.call(d,b,c,a,"info")},warning:function(b,c,a){return d.call(d,b,c,a,"warning")},error:function(b,c,a){return d.call(d,b,c,a,"error")},success:function(b,c,a){return d.call(d,b,c,a,"success")}}});
k.when("A","jQuery","logging","dv-ajax-chunk","dv-ajax-widgets","dv-ux","aiv-client-side-metrics").register("dv-ajax-handler",function(e,b,d,l,g,h,c){var a=d.create("dv-ajax-handler"),f;f=function(b){this.options=b;this.nodes=[];a.debug("new AjaxHandler with",b);b=b.loggingName?b.loggingName:"dvweb-widget-reload-"+b.widgets.join("+");this.widgetMetrics=c.create({scope:b});a.debug("new AjaxHandler with",b,this.widgetMetrics)};f.prototype.callAjax=function(){var a=this,c=a.options.widgets.length,f=
b.Deferred();if(a.options.asin)return a.prepareWidgetsForRefresh(),a.widgetMetrics.ajaxStart(),e.ajax(a.options.url,{params:{asin:a.options.asin,widgets:a.options.widgets},chunk:function(b){b=l(b,a.options.widgets,a.options.DOMRootID);b.isValid?(e.trigger("dv:ajax:chunk:success:"+a.options.DOMRootID),b=g(b),b=b.reloadWidget(a.options.reloadOptions),1>--c&&b&&b.done(function(){a.chunksReplaced(f)})):1>--c&&a.chunksReplaced(f)},success:function(b,c,f){a.handleAjaxSuccess();a.widgetMetrics.ajaxSuccess({xhr:f})},
error:function(){a.removeUILock();a.options.reloadOnFailure&&(u.location.href="/gp/product/"+a.options.asin)},timeout:1E4}),f.promise()};f.prototype.chunksReplaced=function(a){a.resolve();this.widgetMetrics.ajaxDone()};f.prototype.handleAjaxSuccess=function(){this.removeUILock()};f.prototype.removeUILock=function(){for(var a=0,b=this.nodes.length,c;a<b;a++)c=this.nodes[a],h.enable(c)};f.prototype.updateUrl=function(){"function"===typeof u.history.replaceState?u.history.replaceState(this.options,this.options.title,
"/gp/product/"+this.options.asin):u.location.hash="#!"+this.options.asin};f.prototype.prepareWidgetsForRefresh=function(){var a,c=this.options.DOMRootID,f;for(a=0;a<this.options.widgets.length;a+=1)f=this.options.widgets[a],f=c?b("#"+c+" ."+f):b("#"+f),h.disable(f),this.nodes.push(f)};return function(a){return new f(a)}});k.when("jQuery","A").register("dv-ajax-chunk",function(e,b){var d;d=function(b,g,h){this.isValid=!1;this.expectedWidgets=g;e.isArray(b)&&3===b.length&&(this.id=b[1],this.data=b[2],
this.DOMRootID=h,this.validateChunk())};d.prototype.validateChunk=function(){-1!==e.inArray(this.getChunkRawID(),this.expectedWidgets)&&this.getChunkData()&&(this.isValid=!0)};d.prototype.getChunkData=function(){return e.trim(this.data)};d.prototype.getChunkRawID=function(){return this.id};d.prototype.getDOMSelector=function(){var b=this.getChunkRawID();return this.DOMRootID?e("#"+this.DOMRootID+" ."+b):e("#"+b)};return function(b,e,h){return new d(b,e,h)}});k.when("A","logging","dv-ux").register("dv-ajax-widgets",
function(e,b,d){var l=b.create("dv-ajax-widgets"),g,h;g=function(b){this.nodeID=b.getChunkRawID();this.widgetHTML=b.getChunkData();this.$node=b.getDOMSelector()};g.prototype.reloadWidget=function(b){var a=this;if(a.$node.length)return h=d.replaceContent(a.$node,a.widgetHTML,b),h.done(function(){l.debug("dv:ajax:chunk:replaced:"+a.nodeID);e.trigger("dv:ajax:chunk:replaced:"+a.nodeID)}),h};return function(b){return new g(b)}});k.when("A","dv-ajax-handler","ready").register("dv-ajax-reload",function(e,
b){var d=e.$,l={widgets:"dv-dp-title-content dv-dp-left-content dv-action-box dv-episode-list dv-center-aiv dv-customer-reviews".split(" "),reloadOnFailure:!1,title:document.title,url:"/gp/video/apps/ajax-detail-page",reloadOptions:{timeToFadeOut:0}};return{getWidgets:function(e){e=d.extend({},l,e);return b(e).callAjax()}}});k.when("dv-ajax-reload").register("ajax-reload",function(e){return e});k.when("A","jQuery","logging","aiv-util-event","a-modal","dv-modal-stack","dv-modal-templates-ready").register("aiv-modal",
function(e,b,d,l,g,h){function c(c){var d=a(c);c=b("\x3cdiv/\x3e").attr({id:d.id});var E=g,v={},w={},v={},k=[],C=[],r;G&&e.capabilities.mobile&&d.hasScrollableContent&&(E=G,J=!0);var v=d.id,u=f(d),z=t(d),A=p(d),D=J?!1:!!d.hideHeader,N=y(d),I=d.cache||!1,K;K="dark"===d.theme?"none":d.padding;var M=d.maxWidth||d.width||400,L;L="dark"===d.theme?!0:!1;v={name:v,url:u,content:z,header:A,hideHeader:D,footer:N,cache:I,width:"90%",padding:K,"max-width":M,closeButton:L?!1:x(d)};r=E.create(c,v);n.debug("created modal with args:",
v,r);l.bestowEvents(w);q(d.id,w);H(d,w,k,C);r._display=r.show;v={on:B(w),getName:function(){return d.id},_show:function(){r._display()},show:function(){h.add(r);return r},showImmediate:function(){h.replaceTop(r)},remove:function(){n.debug("remove: "+d.id,r,d);F(k,C);E.remove(d.id)}};b.extend(r,v);if("dark"===d.theme||"none"===d.padding)r.on("afterShow",function(a){a=r.$popover;var b=a.find(".a-popover-inner, .a-secondary-view-inner");a.find(".a-popover-wrapper").addClass("dv-aui-dark-wrapper");b.addClass("dv-modal-wrapper-dark");
n.debug("afterShow",d);b.css({padding:0})}),r.on("ajaxContentLoaded",function(a){r.$popover.append(m(d.theme))});r.on("afterHide",function(a){E.remove(d.id)});r.on("closeModal",function(a){E.remove(d.id)});r.on("optOut",function(a){a.url&&e.get(a.url+a.checked)});return r}function a(a){var c;c=b(a.selector||"#"+a.id).data("dv-modal");var f={};A||(z.submitTemplate=b(D.submitTemplate).html(),z.cancelTemplate=b(D.cancelTemplate).html(),z.linkTemplate=b(D.linkTemplate).html(),z.checkboxTemplate=b(D.checkBoxTemplate).html(),
n.debug("_init:",z),A=!0);b.extend(!0,f,c,a);f.originalId=f.id||f.name;f.id=(f.id||f.name)+"_"+I++;n.debug("getOptions:",{args:a,dataAttributes:c,options:f});return f}function f(a){var c="",f=a.url;if(f)return a.urlParameters&&(c=f.match(/\?/)?"\x26":"?",c+=b.param(a.urlParameters)),f+c}function t(a){var c,f;(f=a.content)||(f=["#a-popover-",a.name].join(""),c=b(f),n.info("element: "+f,c),f=c.length?c.html():"");if(!f){f="";c=a.url;var d=b(a.selector||"#"+a.originalId);n.info({url:c,element:d});c||
(f=d.html(),n.debug("_createModal: no url or content, element html",f))}n.info("_getContent",f);c=f;f=a.theme;if(!c)return"";f&&(d="dv-modal-wrapper-"+f,c=b("\x3cdiv /\x3e").addClass(d).append(c),x(a)&&c.append(m(f)),c=c[0]);return c}function m(a){a="dv-modal-close-button-"+a;return b('\x3cbutton type\x3d"button" role\x3d"button" data-action\x3d"a-popover-close" class\x3d"a-declarative"\x3e\x3cspan\x3eX\x3c/span\x3e\x3c/button\x3e').addClass(a)}function p(a){var b=a&&a.header||{};a=a&&a.hideHeader;
n.info("hideHeader:",a,b);return a?"":b.text||""}function y(a,c){var f="",d=a.buttons,h={},e=a.id;n.debug("_getFooter args:",a);d&&b.each(d,function(a,b){var c=v({id:e,elemOptions:b,template:z[b.type+"Template"]});n.debug("_getFooter buttonObj:",c);f+=c.html});a.optOut&&a.optOut.url&&(h=v({id:e,elemOptions:{type:"checkbox",text:a.optOut.text},template:z.checkboxTemplate}),f+=h.html);return f}function B(a){return function(b,c,f){n.debug("on:",a,b,c,f);a.on([b],c,f)}}function x(a){var b=!1;"undefined"!==
typeof a.closeButton?b=a.closeButton:"undefined"!==typeof a.showCloseButton&&(b=a.showCloseButton);return!!b}function q(a,c){b.each(u,function(b,f){e.on("a:popover:"+f+":"+a,function(a){c.fire(f,a)})})}function H(a,c,f,d){n.debug("_addEventListeners",a,c,f,d);a.optOut&&a.optOut.url&&(C("#"+a.id+"-checkbox","optOut",{url:a.optOut.url},c),d.push({id:a.id}));a.buttons&&b.each(a.buttons,function(b,d){var h=d.id||a.id+"-"+d.type,h={name:h,id:"#"+h,eventArgs:d.eventArgs,customEvent:d.customEvent||"dv:dv-modal:"+
d.type,customActionEndpoint:d.customActionEndpoint};r(h,c,a.isDeclarative);f.push(h)})}function v(a){var b=a.elemOptions||{},c=a.template||"",f={};n.debug("_getFooterUIElement args:",a);f.html="";f.name=b.id||a.id+"-"+b.type;f.id="#"+f.name;f.text=b.text;f.url=b.url;f.text&&c&&(f.html=w(c,f.name,f.text,f.url));n.debug("_getFooterUIElement element:",f);return f}function w(){var a=Array.prototype.shift.call(arguments),b=arguments,a=a.replace(/(\r\n|\n|\r)|(^\s+|\s+$)/gm,"");n.debug("_formatTemplate:",
a,b);if(a)return a.replace(/\{(\d+)\}/g,function(a,c){return"undefined"!==typeof b[c]?b[c]:a});n.error("Template missing",b)}function C(a,c,f,d){n.debug("_addCheckBoxEventListener:",a,c,f);b("body").delegate(a+" input[type\x3d'checkbox']","change",function(){f.checked=!!this.checked;n.debug(a+" checkbox changed",f);d.fire(c,f)})}function r(a,c,f){n.debug("_addButtonEventListener button:",c,a);b("body").delegate(a.id,"click",function(){f?e.trigger(a.customEvent,a.eventArgs):c.fire(a.customEvent,a.eventArgs)})}
function F(a,c){n.debug("_removeEventListeners",a,c);b.each(a,function(a,c){b("body").undelegate(c.id,"click")});b.each(c,function(a,c){b("body").undelegate(c.id+" input[type\x3d'checkbox']","change")})}var n=d.create("aiv-modal"),u=["afterHide","afterShow","close","ajaxContentLoaded"],D={submitTemplate:"#SubmitTemplate",cancelTemplate:"#CancelTemplate",linkTemplate:"#LinkTemplate",checkBoxTemplate:"#CheckBoxTemplate"},z={},A=!1,I=0,J=!1,G;k.when("a-secondary-view").execute(function(a){G=a});e.declarative("aiv-modal",
"click",function(b){b=b.data;var f=a(b),d;b.isDeclarative=!0;n.debug("declarative data:",b);d=c(b);f.showImmediately?d.showImmediate():d.show();e.on("aiv:modal:close:declarative",function(){d.remove();e.off("aiv:modal:close:declarative")})});b("body").delegate('[data-action\x3d"aiv-modal"] a',"click",function(a){a.preventDefault()});return{create:c}});k.when("A","jQuery","logging").register("dv-modal-stack",function(e,b,d){function l(b){if(!a(b)){var d=b.attrs("name");f.debug("[add]",d,g());b.on("afterHide",
c);m[d]=!0;t.unshift(b);g()||h(b,0)}}function g(a){if("undefined"===typeof a)return k;f.debug("[_isActive] set",a);k=a}function h(a,b){f.debug("[_displayModal]",a);g(!0);a._show()}function c(a){e.delay(function(){var a,b;b=t.pop();f.debug("[_finishedHiding]",t.length,b);b&&(b=b.attrs("name"),m[b]=!1);g(!1);if(b=t.length)a=t[b-1],h(a,600);f.debug("[_finishedHiding] nextModalInQueue",a)},"undefined"!==typeof a.delay?a.delay:600)}function a(a){for(var b=t.length,c=0;c<b;c++)if(t[c]===a)return f.debug("[_contains] stack already contains",
a,t),!0;return!1}var f=d.create("dv-modal-stack"),t=[],m={},k=!1;return{add:l,replaceTop:function(b){if(!a(b))if(0===t.length)l(b);else{var d=b.attrs("name");f.debug("[addAsNext]",d,g());m[d]=!0;b.on("afterHide",c);d=t.pop();t.push(b);t.push(d);d.remove();h(b,0)}},_internal:{_isActive:g,_types:m,_stack:t,_displayModal:h,_afterHide:c}}});k.when("dv-get-reftag-from-url","dv-send-analytics","dv-url-param","dv-get-elem-by-alias").register("dv-utilities",function(e,b,d,l){return{getRefTagFromURL:e,sendAnalytics:b,
urlParam:d,getElemByAlias:l}});k.register("dv-get-reftag-from-url",function(){return function(e){if(e&&(e=e.match(/\bref_?=([^?&]*)\b/i))&&2<=e.length)return e[1]}});k.when("jQuery").register("dv-send-analytics",function(e){return function(b){b&&e.ajax({url:"/gp/video/widgets/main-section/ajax/analytics.html/ref\x3d"+b,data:{},dataType:"json",timeout:1E4})}});k.register("dv-url-param",function(){var e;return function(b){if(!e){e={};for(var d=(document.location.search||"").substring(1).split("\x26"),
l=0;l<d.length;l++){var g=d[l].split("\x3d");e[g[0]]=g[1]}}return b?e[b]:e}});k.when("A","jQuery").register("dv-get-elem-by-alias",function(e,b){return function(d,e){if(d||e)return b(d).filter(function(d,h){var c=b(h).data("aliases");return!(!c||-1===b.inArray(e,c.split(",")))})}});k.when("A","jQuery","logging").register("dv-content",function(e,b,d){function l(c,a){g.info({element:c,argsObj:a});var f=b.extend(!0,{},h,a),d="."+f.className,f=b("\x3c"+f.wrapperTag+" /\x3e").addClass(f.className),e=c.children(d);
e.length||(c.wrapInner(f),e=c.children(d).css({overflow:"hidden"}));return e}var g=d.create("dv-content"),h={wrapperTag:"div"};return{replaceContent:function(c,a,f){function d(){x.removeAttr("style");k.resolve();"function"===typeof q.callback&&q.callback()}function h(){e.animate(x,{opacity:1,top:0},q.timeToFadeIn,q.easing,d)}g.info({element:c,content:a,args:f});var k=b.Deferred(),y=b(a),B=c.height(),x=l(c,{className:"js-dv-replace-content-wrapper"}),q={};b.extend(!0,q,{timeToFadeIn:300,timeToFadeOut:200,
timeToResize:200,easing:"ease-in-out",fadeInMovePercent:.15,readyToMeasureCallback:null,callback:null},f);!c instanceof b&&g.error("replaceContent $element is not a jQuery object",c);e.animate(x,{opacity:0},q.timeToFadeOut,q.easing,function(){x.empty().append(y);"function"===typeof q.readyToMeasureCallback&&q.readyToMeasureCallback(x);var a={height:x.height(),top:0*q.fadeInMovePercent};x.height(B).css({position:"relative"});e.animate(x,a,q.timeToResize,q.easing,h)});return k.promise()},wrapContent:l,
hideContent:function(b,a,f){b.length&&(b=l(b,{className:"js-dv-hide-content-wrapper"}),e.animate(b,{opacity:0}))},showContent:function(b,a,f){if(b.length){var d=b.find(".js-dv-hide-content-wrapper");d.length&&e.animate(d,{opacity:1},function(){d.removeAttr("style")})}}}});k.when("A","jQuery","logging").register("dv-extendable-element",function(e,b,d){var l=d.create("dv-extendable-element"),g=function(b){l.info(b);this.$element=b};g.prototype.element=function(){l.info(this.$element);return this.$element};
g.prototype.addBehaviours=function(){var d=this,c=Array.prototype.slice.call(arguments);l.debug(c);b.each(c,function(a,b){for(var c in b)b.hasOwnProperty(c)&&(d[c]=d.extensify(b[c],c))})};g.prototype.extensify=function(b){var c=this;l.info(b);return function(){var a=Array.prototype.slice.call(arguments);a.unshift(c.$element);c._value=b.apply(this,a);return c}};g.prototype.value=function(){l.info(this);return this._value};return function(b){l.info(b);var c=Array.prototype.slice.call(arguments,1),a=
new g(b);c&&a.addBehaviours.apply(a,c);return a}});k.when("A","jQuery","logging","dv-content").register("dv-interactive",function(e,b,d,l){var g=d.create("dv-interactive"),h={disableOpacity:.2,useWrapper:!0},c=b("\x3cdiv /\x3e").addClass("dv-disable-overlay js-dv-disable-overlay");return{disable:function(a,f){g.debug(a);var d=b.extend(!0,{},h,f),e,k;a&&a.length&&!a.find(".js-dv-disable-overlay").length&&(k=c.clone(),k.click(function(a){a.preventDefault()}),d.useWrapper?(e=l.wrapContent(a,{className:"js-dv-disable-wrapper"}),
e.animate({opacity:d.disableOpacity},function(){e.css({visibility:"hidden"})}),a.addClass("dv-disable-wrapper").append(k)):a.append(k))},enable:function(a){var b;g.debug(a);a&&a.length&&(a.find(".js-dv-disable-overlay").remove(),b=a.find(".js-dv-disable-wrapper"),b.css({visibility:"visible",opacity:0}),b.animate({opacity:1},function(){b.removeAttr("style")}))}}});k.when("A","jQuery","logging").register("dv-spinner",function(e,b,d){function l(b){return!!b.find("."+a.spinnerWrapper).length}function g(){return'\x3cdiv class\x3d"dv-spinner"\x3e\x3c/div\x3e'}
var h=d.create("dv-spinner"),c={theme:"light",size:"medium"},a={spinnerContainer:"dv-spinner-container",spinnerWrapper:"dv-spinner-wrapper"};return{addSpinner:function(f,d){h.debug(f,d);if(!l(f)){var e=b.extend(!0,{},c,d);h.debug(e.theme,e.size);var e=b(g()),k=a.spinnerWrapper;h.debug(e,k);e=b("\x3cdiv /\x3e").addClass(k).append(e).clone();f.addClass(a.spinnerContainer).append(e)}},removeSpinner:function(b){b.length&&(b.find("."+a.spinnerWrapper).remove(),b.removeClass(a.spinnerContainer))},hasSpinner:l,
getSpinner:g,getSpinnerWrapper:function(b){return b.find("."+a.spinnerWrapper)}}});k.when("A","jQuery","logging","dv-content").register("dv-text",function(e,b,d,l){var g=d.create("dv-replace-text");return{replaceText:function(d,c,a){function f(){g.info("cleanUp",d);v.remove();m.removeAttr("style").removeClass("js-dv-replace-text-new").addClass("js-dv-replace-text-wrapper");d.height("auto").removeClass("js-dv-replace-text-progress");w.callback()}g.info(d,c,a);var k=b.Deferred(),m=b(c),p=d.outerWidth(),
y=d.outerHeight(),B=d.css("padding-top"),x=d.css("padding-bottom"),q=d.css("padding-left"),H=d.css("padding-right"),v=l.wrapContent(d,{className:"js-dv-replace-text-wrapper",wrapperTag:"span"}),w={},C={},r={},F={},n={};b.extend(!0,w,{reverse:!1,easing:"ease-out",timeToChange:150,callback:function(){k.resolve()}},a);!d instanceof b&&g.error("replaceContent $element is not a jQuery object",d);m.length||g.error("replaceContent $content is not an element",c);d.hasClass("js-dv-replace-text-progress")?
v.html(c):(C={position:"absolute",width:p,height:y,left:0,opacity:1,top:0},r={top:w.reverse?y:-y},F={position:"absolute",width:p,height:y,paddingBottom:x,paddingTop:B,paddingLeft:q,paddingRight:H,top:w.reverse?-y:y,left:0,opacity:0},n={top:0,opacity:1},d.css({position:"relative",height:y}).addClass("js-dv-replace-text-progress"),v.css(C),m.addClass("js-dv-replace-text-new").css(F),d.append(m),e.animate(v,{opacity:0},w.timeToChange/2,w.easing),e.animate(v,r,w.timeToChange,w.easing),e.animate(m,n,w.timeToChange,
w.easing,f));return k.promise()}}});k.when("jQuery","logging","dv-extendable-element","dv-content","dv-text","dv-interactive","dv-spinner").register("dv-ux",function(e,b,d,l,g,h,c){b.create("dv-ux");return{disable:h.disable,enable:h.enable,addSpinner:c.addSpinner,removeSpinner:c.removeSpinner,getSpinner:c.getSpinner,getSpinnerWrapper:c.getSpinnerWrapper,replaceText:g.replaceText,replaceContent:l.replaceContent,wrapContent:l.wrapContent,hideContent:l.hideContent,showContent:l.showContent}});k.when("jQuery",
"logging","dv-extendable-element","dv-content","dv-text","dv-interactive","dv-spinner").register("dv-ux-mixins",function(e,b,d,l,g,h,c){b.create("dv-ux");return{extendable:d,content:l,text:g,interactive:h,spinner:c}});k.when("A","jQuery","logging","dv-ux").register("dv-buttons",function(e,b,d,l){function g(a,c,d){c=b("\x3cspan /\x3e").append(c);l.replaceText(a.find("."+p.buttonText),c,{reverse:d})}function h(a,b,c,d){b&&(a.removeClass([p.confirm,p.processing,p.primary].join(" ")),(b=p[b]||"")&&a.addClass(b));
c&&g(a,c,d)}function c(){k.log("[resetConfirmButtons]");var d=b(".dv-confirm");d.length&&d.each(a);m&&b(document).unbind("click",c)}function a(a,c){var d=b(c),f=d.data("orinalText");h(d,"primary",f,!0)}function f(a){if(!a.data("orinalText")){var b=a.text();a.data("orinalText",b)}}var k=d.create("dv-button"),m=e.capabilities.touch,p={confirm:"dv-confirm av-button--confirm",processing:"js-dv-processing dv-button-processing",primary:"dv-oneclick",buttonText:"dv-button-text"};return{buttonContent:g,buttonState:h,
addProcessingState:function(a,c){k.log("[addButtonProcessingState]");a.each(function(a,d){f(b(d));h(b(d),"processing",c)})},resetButtonsOriginalState:function(b){b.length&&b.each(a)},addConfirmState:function(a,d){k.log("[addButtonConfirmState]");a.each(function(a,c){d&&f(b(c));h(b(c),"confirm",d)});m&&b(document).bind("click",c)},resetConfirmButtons:c}});k.when("A").register("dv-analytics",function(e){var b=e.$;return{log:function(d,e,g){var h="",c="",a="",f="";g=null!==g?g:{};"undefined"!==typeof g.pageType&&
(h=g.pageType);"undefined"!==typeof g.subPageType&&(c=g.subPageType);"undefined"!==typeof g.store&&(a=g.store);"undefined"!==typeof g.requestId&&(f=g.requestId);b.ajax({url:"/gp/video/analytics/clickstream-logger.html",data:{asin:null!==d?d:"",pageType:h,subPageType:c,pageAction:null!==e?e:"",tabId:a,pageRequestId:f},dataType:"json",type:"POST",timeout:1E4})},recordWeblab:function(d,e,g){b.ajax({url:"/gp/video/analytics/weblab-logger.html",data:{weblab:d,treatment:e,rid:g.requestId},dataType:"json",
type:"POST",timeout:1E4})},constants:{PLAY_TRAILER:"PlayTrailer",PLAY_STREAM:"PlayStream"}}});k.when("A","jQuery","logging","aiv-modal").register("dv-async",function(e,b,d,l){return{create:function(g,h){function c(a){var b="";a&&"function"===typeof a&&(b=a.name,b||(b=(a=/^function\s+([\w\$]+)\s*\(/.exec(a.toString()))?a[1]:""));return b}function a(a,b){l.create({id:b}).show();q.error(a)}function f(){return{customError:function(){},timeout:function(b,c,d){a(d,"dv-modal-ajax_timeout")},error:function(b,
c,d){a(d,"dv-modal-ajax_error")},abort:function(a,b,c){q.warn("abort")},parsererror:function(b,c,d){a(d,"dv-modal-ajax_error")}}}function t(a){var b=d.create([x,c(a)].join(":"),h||k);return function(){try{a.apply(this,arguments)}catch(c){b.error(c)}}}function m(a){var c=[200,302],d=b.extend({},f(),a);return{success:function(a){q.error("done method must be overridden")},error:function(a,f,e){0>b.inArray(parseInt(a.status,10),c)&&q.warn(a.status);if(f&&"function"===typeof d[f])d[f](a,f,e);else d.error(a,
f,e);d.customError(a,f,e)}}}function p(a,c,d){var f=0,e=d&&d.maxRetrys||0;d=m(d);var h={},g,l;b.extend(h,{accepts:void 0,contentType:void 0,cache:!1,indicator:"",method:"post",params:{},timeout:1E4,withCredentials:!0},d,c);q.debug(h);h.success=t(h.success);g=t(h.error);h.error=g;l=function(){q.log(f);e>++f?h.error=l:h.error=g;y(a,h)};e>f&&(h.error=l);y(a,h)}function y(a,c){a.match("^(/|"+(u.location.protocol+"//"+u.location.host)+")")?e.ajax(a,c):b.ajax(a,B(c))}function B(a){q.debug("convertOptions",
a);var c={data:a.params,success:a.success,error:a.error};b.support.cors?(c.dataType="json",c.type="POST",c.crossDomain=!0,c.xhrFields={withCredentials:!0}):(c.dataType="jsonp",c.type="GET",c.jsonpCallback=a.jsonpCallback);return c}var x=g||"dv-async",q=d.create(x,h||k);return{wrap:t,delay:function(a,b){e.delay(t(a),b)},ajax:p,get:function(a,b,c,d){c=c||{};c.method="get";c.success=b;return p(a,c,d)},post:function(a,b,c,d,f){d=d||{};d.method="post";d.params=b;d.success=c;return p(a,d,f)},deferred:function(){function a(b,
c){return function(a){b(t(a));return c}}var c=b.Deferred(),d=c.promise();b.each(["done","fail","always","then"],function(b,c){"then"===c?d.then=function(a,b){d.done(a).fail(b);return d}:d[c]=a(d[c],d)});c.promise=function(){return d};return c}}}}});k.when("logging").register("aiv-client-side-metrics",function(e){var b=e.create("aiv-client-side-metrics"),d=u.uet,l=u.ues,g=u.uex,h=u.ue,c=function(a){b.log("[CSM] new with options",a);this.scope=a&&a.scope};c.prototype.record=function(a,c){b.log("[CSM] uet "+
this.scope+" "+a,c);"function"===typeof d&&d(a,this.scope,c)};c.prototype.set=function(a,c){b.log("[CSM] ues "+this.scope+" "+a,c);"function"===typeof l&&l(a,this.scope,c)};c.prototype.publish=function(a,c){b.log("[CSM] uex "+this.scope+" "+a,c);"function"===typeof g&&g(a,this.scope,c)};c.prototype.counter=function(a,c,d){b.log("[CSM] ue.count "+a+" "+c);c=c||1;d=d||{scope:this.scope};h&&"function"===typeof h.count&&h.count(a,(h.count(a,void 0,d)||0)+c,d)};c.prototype.timeOfClick=function(a){this.record("tc",
a)};c.prototype.experiment=function(a){this.record("x",a)};c.prototype.calculationEnd=function(a){this.record("pc",a)};c.prototype.clickToNavStart=function(a){this.record("ns",a)};c.prototype.clickToNavEnd=function(a){this.record("ne",a)};c.prototype.clickToBodyBegin=function(a){this.record("bb",a)};c.prototype.clickToATF=function(a){this.record("af",a)};c.prototype.clickToCF=function(a){this.record("cf",a)};c.prototype.clickToBodyEnd=function(a){this.record("be",a)};c.prototype.requestId=function(a){this.set("id",
a)};c.prototype.startTime=function(){this.set("t0",new Date)};c.prototype.baseOnClientTime=function(){this.set("ctb","1")};c.prototype.clickToPageLoaded=function(a){this.publish("ld",a)};c.prototype.ajaxStart=function(a){this.timeOfClick(a)};c.prototype.ajaxSuccess=function(a){var b=a.requestId;a=a.xhr;!b&&a&&"function"===typeof a.getResponseHeader&&(b=a.getResponseHeader("x-amz-id-1"));this.requestId(b);this.startTime();this.baseOnClientTime()};c.prototype.ajaxDone=function(a){this.clickToBodyEnd(a);
this.clickToPageLoaded(a)};return{create:function(a){return new c(a)}}});k.when("A","jQuery").register("dv-reftag",function(e,b){function d(d){b.ajax({url:"/gp/video/widgets/main-section/ajax/analytics.html/ref\x3d"+d,data:{},dataType:"json",timeout:1E4})}e.declarative("dv-record-reftag","click",function(b){b.data&&b.data.reftag&&d(b.data.reftag)});return{record:d}});k.when("jQuery").register("dv-eventBinder",function(e){return{bind:function(b){b=b||document;this._eventRegistry=this._eventRegistry||
[];var d=this,l=/^\s*(.+)\s+(\S+)\s*$/,g=function(a,c,h){var g=function(a,b){a.source=e(this);h.call(d,a,b)};if(a)if(e(b).on)e(b).on(c,a,g);else e(b).delegate&&e(b).delegate(a,c,g);else e(b).bind(c,g);d._eventRegistry.push({baseElement:b,selector:a,eventName:c})},h;for(h in this){var c=h.match(l);c&&this[h]&&"function"===typeof this[h]&&g("subscribe"!==c[1]?c[1]:void 0,c[2],this[h])}},unbind:function(){for(var b=this._eventRegistry.length-1;0<=b;b--){var d=this._eventRegistry[b];d.selector?e(d.baseElement).off?
e(d.baseElement).off(d.eventName,d.selector):e(d.baseElement).undelegate&&e(d.baseElement).undelegate(d.selector,d.eventName):e(d.baseElement).unbind(d.eventName);this._eventRegistry.splice(b,1)}}}});k.when("A","jQuery","logging").register("dv-form",function(e,b,d){var l=d.create("dv-form");return{data:function(d,e){l.debug(d,e);var c=d.find("input").serializeArray(),a={};b.each(c,function(b,c){c.name&&(a[c.name]=c.value)});return a}}});k.when("jQuery","logging","dv-async").register("promise-pipeline",
function(e,b,d){return{create:function(l,g,h){function c(a){m.errors=m.errors||[];f.error(a);m.errors.push(a)}function a(b){var d,h,g;if(b>=k.length)p.resolve(m);else if(d=k[b]||{},g=[d.name,"step:",b].join(" "),d.getPromise&&"function"===typeof d.getPromise){f.debug(g+" got promise",{step:b,currentStep:d,options:m});try{h=d.getPromise(m),h.done(function(c){e.extend(!0,m,c);f.debug(g+" done",m,c);a(++b)}),h.fail(function(a){e.extend(!0,m,a);f.debug(g+" fail",m,a);p.reject(m)})}catch(l){c(l),p.reject(m)}}else c(g+
" getPromise is not a function"),a(++b)}g=g||"promise-pipeline";var f=b.create(g,h);h=d.create(g,h);var k=l.promises,m=l.options,p=h.deferred();a(0);return p.promise()},step:function(b,e,h){var c=d.create(b,h);return{name:b,getPromise:function(a){var b=c.deferred();e(b,a);return b.promise()}}}}});k.when("logging").register("dv-register-once",function(e){var b=e.create("dv-content");return function(d,e){k.now(d).execute(function(g){if("undefined"!==typeof g)b.info("Tried to re-register "+d,e);else try{"function"===
typeof e?k.register(d,e):k.declare(d,e)}catch(h){b.info("Tried to re-register "+d,e)}})}});k.when("dv-register-once").register("av-register-once",function(e){return e});k.when("A","jQuery","logging").register("aiv-util-event",function(e,b,d){var l=d.create("aiv-util-event");return{bestowEvents:function(d){var e={};d.fire=function(c,a){var d,g,k,p;d="string"===typeof c?c:c.type;l.log("[event] fire",d,c,a);if(e.hasOwnProperty(d))for(d=e[d],p=0;p<d.length;p+=1)k=d[p],g=k.method,"string"===typeof g&&
(g=this[g]),k=b.extend(!0,{},k.argsObj,a),g.call(this,k);return this};d.on=function(b,a,d){l.log("[event] on",b,a,d);a={method:a,argsObj:d};e.hasOwnProperty(b)?e[b].push(a):e[b]=[a];return this};return d}}});"use strict";k.when("jQuery","logging","dv-register-once").register("av-widget-config",function(e,b,d){function l(b){g.debug(b);this.name=b}var g=b.create("dv-widget-config",k);l.prototype={get:function(b){var c=e.parseJSON(e("#av-wconf-"+this.name).html());g.debug("widget: "+this.name,b,JSON.stringify(c));
return"undefined"!==typeof b?c[b]:c}};return{declare:function(b){g.debug(b);d(b,new l(b))}}});"use strict";k.when("A","jQuery","logging","dv-ux","av-ui-templates").register("av-action-box-view",function(e,b,d,l,g){function h(b,a){b.length&&e.animate(b,{opacity:0},a,"ease-out",function(){b.remove()})}d.create("av-action-box-view",k);return{mainAddSpinner:function(c){var a=b("#dv-action-box-wrapper"),d=b("#dv-action-box"),h=b("\x3cdiv /\x3e").addClass("dv-action-box-spinner-wrapper").append(g.get("fill-spinner"));
c=b("\x3cdiv /\x3e").addClass("dv-action-box-progress-wrapper").append(h).append(c||"");var h=a.height(),k=c.height();a.append(c.css({top:h/2-k/2}));l.disable(d,{useWrapper:!1});e.animate(d,{opacity:0})},mainReset:function(){var c=b("#dv-action-box-wrapper"),a=b("#dv-action-box"),c=c.find(".dv-action-box-progress-wrapper");e.animate(b("#dv-action-box"),{opacity:100});h(c,300);l.enable(a)},mainUpdate:function(){var c=b("#dv-action-box-wrapper"),a=b("#dv-action-box"),d=c.find(".dv-purchasing-text"),
g=c.find(".dv-action-box-progress-wrapper");h(d,100);l.enable(a);e.animate(b("#dv-action-box"),{opacity:1},300,"ease-out",function(){h(g,300)})},alignSpinner:function(c){var a=c.find(".av-play-box"),d=0<a.length;c=b("#dv-action-box-wrapper").find(".dv-action-box-progress-wrapper");d&&(a=a.position(),c.css({bottom:"auto"}).animate(a,200))}}})});
/* ******** */
(function(a){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,b=d?d("DigitalVideoEpisodeListAssets"):c;b.guardFatal?b.guardFatal(a)(b,window):b.execute(function(){a(b,window)})})(function(a,c,d){a.when("A","jQuery","ready").execute(function(b,a){a("body").delegate(".dv-el-title","click",function(b){b.stopImmediatePropagation();589>a(c).width()&&a(this).closest(".dv-episode-container").toggleClass("dv-el-opened")})})});
/* ******** */
(function(f){var d=window.AmazonUIPageJS||window.P,e=d._namespace||d.attributeErrors,b=e?e("DigitalVideoWebGiftCardAssets"):d;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,d,e){f.when("A","dv-async","aiv-alerts","aiv-modal").register("dv-gift-card",function(b,d,e){var c=b.$,g=d.create("dv-gift-card",f).ajax;({states:{RUNNING:2,READY:1},currentState:null,init:function(){this.id="dv-gift-card";this.addEventListeners();this.currentState=this.states.READY},addEventListeners:function(){var a=
this;c("body").delegate("#gc-giftcard","submit",function(c){c.preventDefault();a.submit()});b.on("dv:modal:click:submit:"+a.id,function(){a.submit()})},submit:function(){var a=this,b,d,e={retJSON:!0};a.currentState!==a.states.RUNNING&&(a.currentState=a.states.RUNNING,b=c("#gc-giftcard"),d=b.attr("action"),e.code=b.find(".dv-gc-input").val(),g(d,{params:e,success:function(b){var c=b.message;b.success?(a.updateGCBalances(b),a.updateModalSuccess(c)):a.updateModalFailure(c);a.currentState=a.states.READY},
error:function(b){a.updateModalFailure(b);a.currentState=a.states.READY}}))},updateModalFailure:function(a){this.showMessage(c(e.error(a,"block","light")))},updateModalSuccess:function(a){this.showMessage(c(e.success(a,"block","light")))},showMessage:function(a){c("#dv-gc-message-wrapper")[0]||this.addMessageWrapper();c("#dv-gc-message-wrapper").html(a)},addMessageWrapper:function(){c("\x3cdiv/\x3e").attr({id:"dv-gc-message-wrapper"}).insertAfter(c("#dv-gc-widget-heading"))},updateGCBalances:function(a){for(var b in a.balances)a.balances.hasOwnProperty(b)&&
c("#dv_gc_balances_"+b).html(a.balances[b])}}).init()})});
/* ******** */
(function(c){var z=window.AmazonUIPageJS||window.P,J=z._namespace||z.attributeErrors,h=J?J("DigitalVideoWebPurchasingAssets"):z;h.guardFatal?h.guardFatal(c)(h,window):h.execute(function(){c(h,window)})})(function(c,z,J){c.when("A","logging","dv-pp-pin-view","aiv-util-event","dv-async").register("dv-pp-pin-controller",function(h,e,k,g,f){var b=e.create("dv-pp-pin-controller"),a=f.create("dv-pp-pin-controller",c),q=h.$,x={strings:{CHECKING_PIN:"Checking Pin...",PIN_INVALID:"The Pin you have entered is invalid, please try again.",
AUTHENTICATION_SUCCESS:"Authentication successful.",AUTHENTICATION_FAILURE:"This pin is not correct, please try again",TOKEN_FAILURE:"Your session has expired, please refresh the page and try again.",BAD_REQUEST:"We had a problem validating your pin, please refresh the page and try again"},urls:{pinCheckUrl:"/gp/video/usdvm/ajax/show_parental_dialog.html",pinAuthUrl:"/gp/video/usdvm/ajax/pin-check.html"},action:"PURCHASE",validationPeriod:1E3,successMsgDuration:200,isTestRun:!1,numPins:5,view:{pinConfig:{numPins:5},
events:{submit:"submitPin",show:"show",hide:"hide",cancel:"cancel",close:"close"}}};return{create:function(f,w){function l(d,m){u.fire(d,m)}function c(){var d=v.getUserPin();(new RegExp("^\\d{"+r.numPins+"}$")).test(d)?(v.createMessage("info",r.strings.CHECKING_PIN),B(d)):(v.createMessage("error",r.strings.PIN_INVALID),v.resetPin())}function e(){var d=p.activeAsin;H(d)?D(d):(delete m[d],l("pinAuthFailure",{asins:d}));delete p.activeAsin}function y(d,a,p){b.debug(d,a,p);d&&(a||(a="UNAUTHORIZED"),m[d]=
I(a,p))}function I(d,a){var m=(new Date).getTime(),p=m+r.validationPeriod;return{getStatus:function(){return d},getTimestamp:function(){return m},isExpired:function(){return p<(new Date).getTime()},getToken:function(){return a}}}function C(d){b.debug(d);if(d)return m[d]||n(d),m[d]}function H(d){b.log("[DV PIN] isAuthorized",d);if(!d)return!1;E(d);return"AUTHORIZED"===C(d).getStatus()&&E(d)?!0:!1}function D(d){var a=C(d);b.log("[DV PIN] handleAsinAuthorization",d,a.getStatus());switch(a.getStatus()){case "ERROR":l("pinAuthFailure",
{asins:d});y(d,"UNAUTHORIZED");break;case "TOKEN_INVALID":l("sessionExpired",{asins:d});y(d,"UNAUTHORIZED");break;case "AUTHORIZED":E(d)?l("success",{asins:d,token:a.getToken()}):(y(d,"UNAUTHORIZED"),D(d));break;case "UNAUTHORIZED":v.trigger(r.view.events.show);p.activeAsin=d;break;case "PENDING":p.callbackHandleAuth=!0;break;default:b.log("[DV PIN] handleAsinAuthorization default",d,a),l("pinAuthFailure",{asins:d}),y(d,"UNAUTHORIZED")}}function E(d){d=C(d);return"AUTHORIZED"!==d.getStatus()?!1:d.isExpired()?
!1:!0}function F(d){d&&"function"===typeof d&&d()}function t(d){b.debug(d);a.ajax(d.url,{params:d.data,success:function(){d.success.apply(this,arguments);F(d.complete)}},{maxRetrys:3,customError:function(a,m,p){l("error");F(d.error);F(d.complete)}})}function B(d){b.debug(d);t({url:r.urls.pinAuthUrl,data:{csrfToken:r.csrfToken,pin:d,asin:p.activeAsin},type:"jsonp",success:G,error:function(){v.createMessage("error",r.strings.AUTHENTICATION_FAILURE)}})}function G(d){var a=p.activeAsin,m;b.log("[DV PIN] performPinAuthenticationSuccess",
d);if(d.success)v.createMessage("success",r.strings.AUTHENTICATION_SUCCESS),y(a,"AUTHORIZED",d.token),v.trigger(r.view.events.hide,{delay:r.successMsgDuration});else{switch(d.error){case "INVALID_CSRF_TOKEN":m=r.strings.TOKEN_FAILURE;break;case "BAD_REQUEST":m=r.strings.BAD_REQUEST;break;case "WRONG_PIN":case "INCORRECT_PIN_FORMAT":m=r.strings.AUTHENTICATION_FAILURE}v.createMessage("error",m);v.resetPin()}}function n(d){y(d,"PENDING");b.log("[DV PIN] performPinRequiredCheck",d);t({url:r.urls.pinCheckUrl,
data:{ASINS:d,csrfToken:r.csrfToken,action:r.action},asin:d,complete:function(){b.log("[DV PIN] performPinRequiredCheck complete",p);p.callbackHandleAuth&&(p.callbackHandleAuth=!1,D(d));l("pinRequiredCheckComplete")},success:function(a){b.log("[DV PIN] performPinRequiredCheck success",a);var m="UNAUTHORIZED";(p.data=a)&&"object"===typeof a&&("BAD_REQUEST"===a.error?m="ERROR":"TOKEN_INVALID"===a.error?m="TOKEN_INVALID":a.pinRequired?(m="UNAUTHORIZED",a=a.numPinsRequired,b.debug(a),a&&(r.numPins=a,
v.setNumViewPins(a))):m="AUTHORIZED");y(d,m)}})}var u={},v,r={},m={},p={};b.log("[DV-PURCH] pin-controller");(function(d,a){b.debug(d,a);q.extend(!0,r,x,d);v=r.isTestRun&&a?a:k.create(r.view);g.bestowEvents(u);v.on(r.view.events.submit,c);v.on(r.view.events.close,e);h.on("dv:purchase:cancel",function(d){delete m[d.asins];delete p.activeAsin})})(f,w);return{on:function(d,a){u.on([d],a)},trigger:l,isAuthorized:H,performPinRequiredCheck:n,getAsinStatus:C,handleAsinAuthorization:D}}}});c.when("A","jQuery",
"logging","aiv-util-event","aiv-modal","aiv-alerts").register("dv-pp-pin-view",function(c,e,k,g,f,b){var a=k.create("dv-pp-pin-view"),q={focusFieldsOnKeyUp:!0,id:"dv-purchase-pin-view",isIosDevice:!1,selectors:{modalSelector:"#dv-pin-pop",pinWrap:"#pin-wrap",continueButton:"#dv-purchase-pin-view-submit",cancelButton:"#dv-purchase-pin-view-cancel",statusMsg:".dv-pin-pop-status-msg"},selectorFragments:{submitSuffix:"-submit"},hasCustomConfig:!1,pinConfig:{numPins:5,numPinInputs:void 0,pinInputParams:{pattern:"[0-9]*",
type:"password",size:"1",maxlength:"1","class":"pinNum"}},events:{submit:"submitPin",show:"show",hide:"hide",close:"close"}};return{create:function(x){function A(b,m){a.log("[PIN-VIEW] trigger",b);G.fire(b,m)}function w(){var b=document.createElement("input"),m=t.pinConfig.pinInputParams,p;a.log("[PIN-VIEW] createInputElem",m);for(p in m)m.hasOwnProperty(p)&&b.setAttribute(p,m[p]);return b}function l(b){a.log("[PIN-VIEW] buildUpPopover",b);v=b.popover;n.$popover=v.$popover;b=n.$popover.find("input.pinNum");
if(!b||!b.length){var m=n.$popover.find(t.selectors.pinWrap),p=t.pinConfig.numPinInputs||t.pinConfig.numPins;a.log("[PIN-VIEW] appendInputs",t);for(b=1;b<=p;b+=1)m.append(w());n.$pins=m.find("input");a.log("[PIN-VIEW] registerEventHandlers");n.$submit=e("#"+u.name+t.selectorFragments.submitSuffix);n.$submit.find("input").click(C);t.focusFieldsOnKeyUp&&(n.$pins.keyup(y),n.$pins.keydown(z))}E()}function k(){a.log("[PIN-VIEW] tearDownPopover",n.$popover);A(t.events.close);F();n.$pins&&n.$pins.remove();
n.$popover&&n.$popover.find("input").unbind();B.submitDisabled=!1;delete n.$popover}function z(b){var m=e(this);b=8===b.which;a.log("[PIN-VIEW] handleKeyDown");b&&((b=0<m.val().length)||m.prev("input").focus().val(""))}function y(b){var m=e(this),p=m.not().is(":last-child"),d=0<m.val().length;b=13===b.which;var l=D().length===t.pinConfig.numPins;a.log("[PIN-VIEW] handleKeyUp");l?B.submitDisabled&&(n.$submit.removeClass("a-button-disabled").find("input").removeAttr("disabled"),B.submitDisabled=!1):
I();b&&l?C():!d||p||l||m.next().focus();B.messageVisible&&F()}function I(){B.submitDisabled||(n.$submit.addClass("a-button-disabled").find("input").attr("disabled","disabled"),B.submitDisabled=!0)}function C(){a.log("[PIN-VIEW] handleSubmit");A(t.events.submit)}function H(b){a.log("[PIN-VIEW] hide",u,b);b&&b.delay?c.delay(function(){u.remove()},b.delay):u.remove()}function D(){var a=[];n.$pins.each(function(b,p){p.value.length&&(1<p.value.length?a=p.value.split(""):a.push(p.value))});return a}function E(){a.log("[PIN-VIEW] resetPin");
n.$pins.val("");c.delay(function(){n.$pins.first().focus()},10);I()}function F(){B.messageVisible=!1;n.$popover&&n.$popover.find(t.selectors.statusMsg).html("")}var t={},B={},G={},n={},u,v;a.log("[PIN-VIEW]");e.extend(!0,t,q,x);a.log("[PIN-VIEW] init",t);g.bestowEvents(G);a.log("[PIN-VIEW] registerCustomEvents");G.on(t.events.show,function(){a.log("[PIN-VIEW] show",u);u=f.create({selector:t.selectors.modalSelector,id:t.id});a.log("[PIN-VIEW] registerAUIModalHandlers");u.on("afterShow",l);u.on("afterHide",
k);u.on("dv:dv-modal:cancel",H);u.show()});G.on(t.events.hide,H);return{getUserPin:function(){return D().join("")},on:function(b,m){a.log("[PIN-VIEW] on",b);G.on([b],m)},trigger:A,createMessage:function(a,m){var p;b[a]&&typeof("function"===b[a])&&(p=b[a](m,"inline","light"),F(),n.$popover.find(t.selectors.statusMsg).html(p),B.messageVisible=!0)},resetPin:E,setNumViewPins:function(a){a&&(t.pinConfig.numPins=a,t.hasCustomConfig?(t.pinConfig.pinInputParams.size=a,t.pinConfig.pinInputParams.maxlength=
a):t.pinConfig.numPinInputs=a)}}}}});c.when("A","jQuery","logging","promise-pipeline","purchase-modal").register("dv-hd-warning",function(h,e,k,g,f){function b(a,b,q){return function(){f.create({id:a,asin:q,deferred:b,continuePurchaseOnSubmit:!0,cancelPurchaseOnCancel:!0,urlParameters:{asin:q}}).show()}}var a=k.create("dv-hd-warning",c),q;c.when("dv-web-player-capabilities").execute(function(b){b(function(b){a.log("[DV-PURCH] hd-warning playerCapabilities",b);q=b.capabilities})});return g.step("dv-hd-warning",
function(f,c){var e,l,g;a.debug("[DV-PURCH] hd-warning",c,q);q&&(l=q.supportsWebPlayback,g=q.supportsHDMovies);a.debug("supportsWebPlayback:",l,"supportsHDMovies:",g);e={showHDWarning:b("dv-modal-hd-content-warning",f,c.asin),showHDCPWarning:b("dv-modal-hdcp-content-warning",f,c.asin),showUnsupportedWarning:b("dv-modal-unsupported-device-warning",f,c.asin),continuePurchase:f.resolve};l?g?c.canShowWebHdcpWarning?e.showHDCPWarning():e.continuePurchase():c.canShowWebHdWarning?e.showHDWarning():e.continuePurchase():
c.showUnsupportedWarning?e.showUnsupportedWarning():c.showDeviceHdWarning?e.showHDWarning():c.showDeviceHdcpWarning?e.showHDCPWarning():e.continuePurchase()},c)});c.when("jQuery","logging","promise-pipeline").register("dv-sign-in",function(h,e,k){e.create("dv-sign-in",c);return k.step("dv-sign-in",function(c,f){f.shouldSignIn?z.location.replace(f.signInUrl):c.resolve()},c)});c.when("A","jQuery","logging","promise-pipeline","purchase-modal","dv-age-verification-data-ready").register("dv-age-verification",
function(h,e,k,g,f){var b=k.create("dv-age-verification",c);return g.step("dv-age-verification",function(a,c){var e=h.state("dv-age-verification-data");b.log("[DV-PURCH] dv-age-verification",c,e);e&&e.isAgeVerificationRequired?f.create({id:"dv-age-verification-modal",asin:c.asin,deferred:a}).show():a.resolve()},c)});c.when("A","jQuery","logging","promise-pipeline","dv-pp-pin-controller","purchase-modal","dv-purchasing-errors").register("dv-pin-verification",function(h,e,k,g,f,b,a){var q=k.create("dv-pin-verification",
c);return g.step("dv-pin-verification",function(b,c){var e=c.pinVerification,l=f.create(e);q.log("[DV-PURCH] pin-verification",e,c);l.on("success",function(a){q.log("Pin Check Success happened with args:",a);b.resolve(a)});l.on("pinAuthFailure",function(a){q.log("Pin Check Failure happened with args:",a);b.reject({reload:!1})});l.on("sessionExpired",function(l){q.log("Pin Check Failure happened with args:",l);b.reject({errors:[a.invalidCSRFToken()],reload:!1})});l.handleAsinAuthorization(c.asin)},
c)});c.when("A","jQuery","logging","promise-pipeline","purchase-call-handler").register("dv-create-order",function(h,e,k,g,f){k.create("dv-create-order",c);return g.step("dv-create-order",function(b,a){var c={deferred:b,endpoint:a.createOrder&&a.createOrder.url,callData:a.purchaseArgs||{},asins:a.asin,ajaxDataType:a.ajaxDataType,purchasingModalText:a.purchasingModalText},e=a.token;e&&(c.callData.pinToken=e);f.create(c).callPurchase()},c)});c.when("A","jQuery","logging","promise-pipeline","purchase-call-handler").register("dv-check-order-status",
function(h,e,k,g,f){k.create("dv-check-order-status",c);return g.step("dv-check-order-status",function(b,a){var c={deferred:b,endpoint:a.checkOrderStatus&&a.checkOrderStatus.url,callData:a.purchaseArgs,asins:a.asin,ajaxDataType:a.ajaxDataType,purchasingModalText:a.purchasingModalText};a.token&&(c.callData.pinToken=a.token);a.orderToken&&(c.callData.orderToken=a.orderToken);f.create(c).callPurchase()},c)});c.when("A","jQuery","logging","dv-async","dv-purchase-fix-up","aiv-client-side-metrics").register("purchase-call-handler",
function(h,e,k,g,f,b){var a=k.create("purchase-call-handler",c),q=g.create("purchase-call-handler",c),x={endpoint:"/gp/video/order/create-order.html",ajaxDataType:"jsonp",ajaxRetries:3,callData:void 0,jsonpCallback:void 0,isOrderStatusCheck:!1},A=b.create({scope:"dvweb-buybox-purchase"}),w=b.create({scope:"dvweb-buybox-orderAction"}),l=b.create({scope:"dvweb-buybox-polling"});return{create:function(b){function c(b){var e=b.action||{},x=b.orderToken;e.deferred=h.deferred;x&&(h.callData.orderToken=
x);a.log("[ajaxPurchase] _ajaxSuccess",navigator.userAgent,b);switch(b.status){case "SUCCESS":h.isOrderStatusCheck?(w.ajaxSuccess({requestId:b.requestId}),w.ajaxDone()):(A.ajaxSuccess({requestId:b.requestId}),A.ajaxDone());h.deferred.resolve({orderToken:b.orderToken});break;case "PENDING":l.counter("dvweb-checkOrderStatus-polling");q.delay(k,e.delay);break;case "ERROR":f.fix(g(e));break;default:f.fix(e)}}function g(a){h.purchasingModalText&&a.modal&&a.modal.header&&a.modal.header.text&&(a.modal.header.text=
a.modal.header.text+" "+h.purchasingModalText);return a}function k(){var b={params:h.callData,success:c,jsonpCallback:h.jsonpCallback},l={maxRetrys:h.ajaxRetries,customError:function(b,c,l){a.error(c,l);h.deferred&&h.deferred.reject()}};A.ajaxStart();q.ajax(h.endpoint,b,l)}var h={};e.extend(!0,h,x,b);a.log("[ajaxPurchase] create",h);return{callPurchase:function(){k()}}}}});c.when("A","jQuery","logging","purchase-modal").register("dv-purchase-fix-up",function(c,e,k,g){var f=k.create("dv-purchase-fix-up");
return{fix:function(b){f.log("[fixUp] errorAction:",b);b||(f.error("no action was passed to errorAction"),b={});b.deferred&&!b.redirectUrl&&b.deferred.reject();b.modal?(f.log("[fixUp] _actionModal:",b),b.modal&&(b.modal.deferred=b.deferred,g.create(b.modal).show())):b.redirectUrl?(f.log("[fixUp] _actionRedirect args:",b),z.location.href=b.redirectUrl):(f.log("[fixUp] _generalError args:",b),g.create({id:"dv-modal-generic-error",cancelPurchaseOnSubmit:!0,deferred:b.deferred}).show())}}});c.when("A",
"jQuery","logging","aiv-modal").register("purchase-modal",function(c,e,k,g){function f(a,e){var f=a.getName(),g=e.deferred;c.on("a:popover:beforeHide:"+f,function(a){b.log("a:popover:beforeHide:"+f+" happened",a,g);g&&g.reject({reload:!1})});a.on("submit",function(c){b.log("[DV-PURCH] purchase-modal submit",c,g);g&&g.resolve();a.remove()});a.on("link",function(c){b.log("[DV-PURCH] purchase-modal link",c,g);var l=c.url;l?z.location.href=l:b.error("purchaseModal link event called without url",c);a.remove()});
a.on("cancel",function(c){b.log("[DV-PURCH] purchase-modal cancel",c,g);g&&g.reject({reload:!1});a.remove()})}var b=k.create("purchase-modal");return{create:function(a){var c={cancel:{customEvent:"cancel",eventArgs:{asin:a.asin,id:a.id,cancelPurchaseOnCancel:"undefined"!==typeof a.cancelPurchaseOnCancel?a.cancelPurchaseOnCancel:!0}},submit:{customEvent:"submit",eventArgs:{asin:a.asin,id:a.id,continuePurchaseOnSubmit:a.continuePurchaseOnSubmit,retryPurchaseOnSubmit:a.retryPurchaseOnSubmit,cancelPurchaseOnSubmit:a.cancelPurchaseOnSubmit}},
checked:{customEvent:"checked",eventArgs:{id:a.id,elemId:a.id+"-check"}}},h;h=(h=e("#"+a.id).data("dv-modal"))&&h.buttons||[];var k={},w,l;for(w=0;w<h.length;w++)l=h[w].type,k[l]=h[w];c=e.extend(!0,{},c,k);c=e.extend(!0,{},{showCloseButton:!1,footer:{},buttons:[c.cancel,c.submit,c.checked]},a);b.log("purchase-modal createModal with options",c);c=g.create(c);f(c,a);return c}}});c.when("dv-sign-in","dv-age-verification","dv-hd-warning","dv-pin-verification","dv-create-order","dv-check-order-status").register("purchase-pipeline",
function(c,e,k,g,f,b){return{start:function(){return[c,e,k,g,f,b]},continuePurchase:function(){return[c,b]}}});c.when("jQuery","logging","aiv-modal").register("dv-purchasing-errors",function(h,e,k){function g(a){this.name="MissingAsin";this.message=a;this.stack=Error().stack}function f(a){this.name="MissingPinToken";this.message=a;this.stack=Error().stack}function b(a){this.name="MissingCSRFToken";this.message=a;this.stack=Error().stack}function a(a){this.name="InvalidCSRFToken";this.message=a;this.stack=
Error().stack}function q(a){this.name="MissingOrderToken";this.message=a;this.stack=Error().stack}function x(a){var b=k.create({id:"dv-modal-session-expired"}).show();w.error(a.message,a.stack);b.on("dv:dv-modal:submit",function(){document.location.reload(!0)})}function A(a){var b=k.create({id:"dv-modal-generic-error"}).show();w.error(a.message,a.stack);b.on("dv:dv-modal:submit",function(){document.location.reload(!0)})}var w=e.create("dv-purchase-errors",c);return{handleError:function(b){b&&(w.log("_handleError",
b),b instanceof a?x(b):A(b))},invalidCSRFToken:function(b){return new a(b)},missingAsin:function(a){return new g(a)},missingPinToken:function(a){return new f(a)},missingCSRFToken:function(a){return new b(a)},missingOrderToken:function(a){return new q(a)}}});c.when("A","logging","promise-pipeline","aiv-modal","dv-purchasing-errors","purchase-pipeline").register("purchase-video",function(h,e,k,g,f,b){function a(a,b){q.log("[DV-PURCH] purchase",a);var e=k.create({promises:b,options:a},"purchase-video",
c);e.done(function(a){q.log("[DV-PURCH] pipeline has finished",a)});e.fail(function(a){q.log("[DV-PURCH] pipeline has failed",a);a&&a.errors&&h.each(a.errors,function(a){f.handleError(a,c)})});return e}var q=e.create("purchase-video",c);return{start:function(c){q.log("[DV-PURCH] start",c);return a(c,b.start())},continuePurchase:function(c){q.log("[DV-PURCH] continue",c);return a(c,b.continuePurchase())}}});c.when("A","jQuery","logging","dv-purchase-data-ready").register("dv-purchase-continue",function(c,
e,k){var g=k.create("dv-purchase-continue");return{checkPurchaseTriggers:function(){g.log("[purchase] checkPurchaseTriggers");var f=e.Deferred(),b=c.state("dv-purchase-continue-data")||{},a=b.purchaseAsin,k=b.purchaseToken,x=b.orderToken;g.log("[purchase] checkPurchaseTriggers state",a,k,x);a&&(k||x)&&e.ajax({url:b.validateTokenUrl,data:{purchasetoken:k},success:function(b){g.log("[purchase] validateActionToken success",b);b.success&&f.resolve({orderToken:x,asin:a})},error:function(a){g.log("[purchase] validateActionToken error",
a);f.reject(a)},dataType:"json"});return f.promise()}}});c.when("A","jQuery","logging","dv-form","dv-ux","dv-ux-mixins","dv-buttons","dv-utilities","dv-purchase-continue","purchase-video","dv-purchase-data-ready").register("dv-purchase-view",function(h,e,k,g,f,b,a,q,x,A){function w(a,b){h.trigger("aiv:modal:close:declarative");n.log(b);n.log(b);var d=b.isSeasonPurchase?e(u.actionBoxContainer):a.parents(u.actionBoxContainer);b.isSeasonPurchase?(H(d.siblings(".dv-el-status-wrapper")),f.hideContent(d.siblings(".dv-el-more-offers"))):
C(b.asin,f.hideContent);F(d,b);d=b.asin;n.log(d);d=I(d);H(d);b.orderToken?(n.log(b),d=A.continuePurchase(b)):(n.log(b),d=A.start(b));J(d)}function l(a){var b=a.parents("form"),b=g.data(b),d=h.state("dv-purchase-data")||{};a=a.find("input").data();return e.extend(!0,{},d,a,{asin:b.asin,pinVerification:{csrfToken:b.csrfToken},purchaseArgs:b})}function z(a){var b=h.state("dv-purchase-view-data")||{};return a?b[a]:b}function J(a){a.done(function(a){n.log("p.done",a);t(a)});a.fail(function(a){n.log("p.fail",
a);t(a)})}function y(a,b){return e(a).filter(function(a,c){return!!e(c).find("[data-asin\x3d"+b+"]")[0]})}function I(a){var b;a=q.getElemByAlias(u.episode,a);a.length&&(b=a.find(".dv-el-status-wrapper"));return b}function C(a,b){var d;d=q.getElemByAlias(u.episode,a);d.length&&b(d.find(".dv-el-more-offers"))}function H(a){a&&a.length&&a.each(function(a,b){f.hideContent(e(b));f.addSpinner(e(b))})}function D(a){a&&a.length&&a.each(function(b,d){f.showContent(a);f.removeSpinner(a)})}function E(a){n.log(a);
if(a=I(a))f.showContent(a),f.removeSpinner(a)}function F(a,c){n.log(a,c);a.length&&a.each(function(a,m){var f=e(m),g=f.hasClass("js-dv-action-box-episode"),f=b.extendable(f),h=e("\x3cp /\x3e").html(c.purchasingText),k=g?{}:{theme:"dark"},g=!(c.isSeasonPurchase&&g);f.addBehaviours(b.interactive,b.spinner);var l=c.asin;"undefined"!==typeof f&&(r[l]=r[l]||[],r[l].push(f));f.disable({disableOpacity:0}).addSpinner(k);g&&f.getSpinnerWrapper().value().append(h)})}function t(a){!1===a.reload?G(a.asin,a.isSeasonPurchase):
B(a)}function B(a){var b=a.purchaseArgs.asin,d=z("pageAsin"),e=q.getElemByAlias(u.episode,b),f=e.attr("id"),g=y(u.mainActionBox,b),k=!!g.length,l=!!e.length,t=a.isSeasonPurchase,r;n.log("resetActionBoxess",a,g,e);c.when("dv-ajax-reload").execute(function(a){var c=(h.state("dv-purchase-data")||{}).widgetRefresh.endpoint;k&&a.getWidgets({asin:d,url:c,loggingName:"dvweb-actionbox-purchase",widgets:["dv-action-box"]});t&&b?r=a.getWidgets({asin:d,url:c,loggingName:"dvweb-season-purchase",widgets:["dv-episode-list"]}):
l&&b&&(r=a.getWidgets({asin:b,url:c,loggingName:"dvweb-episodelist-purchase",widgets:["dv-el-offers","dv-el-more-offers","dv-el-cancel-order","js-ajaxable-episode-status"],DOMRootID:f}));r&&r.done(function(){E(b)})})}function G(c,g){n.log(c,g);var d=g?e(u.actionBoxContainer):y(u.actionBoxContainer,c);d.length&&d.each(function(c,d){var f=e(d),g=f.find(".js-dv-processing");b.extendable(f,b.interactive,b.spinner).removeSpinner().enable();a.resetButtonsOriginalState(g)});g?(D(d.siblings(".dv-el-status-wrapper")),
f.showContent(d.siblings(".dv-el-more-offers"))):(C(c,f.showContent),E(c))}var n=k.create("dv-purchase-view",c),u={mainActionBox:"#dv-action-box",actionBoxContainer:".js-dv-action-box, .js-dv-action-box-episode",actionBoxWrap:".js-dv-action-box-wrap",purchaseButton:".js-purchase-button",episode:".dv-episode-container"},v=h.capabilities.touch,r={};x.checkPurchaseTriggers().done(function(a){var b=y(u.purchaseButton,a.asin);if(0!=b.length){var c=b.first(),c=l(c);n.log(a);a.orderToken&&(c.orderToken=
a.orderToken);w(b,c)}});e("body").delegate(u.purchaseButton,"click",function(b){var c=e(this),c=l(c),d=c.asin;n.log(c);d=y(u.purchaseButton,d);d.hasClass("js-dv-processing")?(n.info("canceled",d),b.preventDefault(),b.stopImmediatePropagation()):(d.hasClass("dv-confirm")||!v?w(d,c):v&&(a.resetConfirmButtons(),a.addConfirmState(d,z("confirmButtonText")),b.stopPropagation()),b.preventDefault())})});c.when("A","logging").register("dv-order-cancellation",function(h,e){var k=e.create("dv-order-cancellation",
c);h.on("cancel-order:dv-self-cancel-modal:submit",function(){k.log("cancel-order:dv-self-cancel-modal:submit");c.when("a-dropdown").execute(function(c){var e=c.getSelect("dv-self-refund-drop-down").val().split(":",2);c=e[0];var e=e[1],b=h.$(".dvSelfCancelModal"),a=b.data("orderCancelBaseUrl"),b=b.data("pageAsin");k.log("orderCancelation",c,e,a);c&&e&&a&&(document.location.href=a+"?orderId\x3d"+c+"\x26asin\x3d"+e+"\x26return_to\x3d/gp/product/"+b)})})})});
/* ******** */
(function(c){var d=window.AmazonUIPageJS||window.P,e=d._namespace||d.attributeErrors,a=e?e("DigitalVideoWebSeasonSelectorAssets"):d;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,d,e){c.when("A","a-dropdown").execute("dv-season-selector",function(a,c){var d=a.$,e=d(".dv-season-selector-drop-down .a-dropdown-prompt"),b=c.getSelect("dv-season-selector"),f=d(".dv-season-selector-drop-down"),g=f?f.data("redirect-link"):"";b&&b.options&&b.options.$select&&e&&(b=
b.options.$select,b=b.find(":selected").data("a-html-content"),e.html(b));a.on("a:dropdown:dv-season-selector:select",function(a){var b=a.value.split(":"),c=b[0],b=b[1];a=d(a.auiItemNode).html();e.html(a);document.location.href=g+c+"?ref_\x3d"+b})})});
/* ******** */
(function(e){var g=window.AmazonUIPageJS||window.P,r=g._namespace||g.attributeErrors,b=r?r("DigitalVideoWebDetailsAssets"):g;b.guardFatal?b.guardFatal(e)(b,window):b.execute(function(){e(b,window)})})(function(e,g,r){e.when("A","logging","aiv-modal","dv-async").register("dv-watchlist-toggle",function(b,c,a,d){function l(a,d){function c(h){var f=h&&"added"===h.status?!0:!1;k.log("recieved wl response",h);1===h.success?b=p(d,f):"csrf_token_was_not_valid"===h.reason?n("dv-modal-session-expired"):m();
h=b("initial");a.val(h);a.attr({disabled:!1}).data({onWatchlist:f})}var b=p(d);return{callWatchlist:function(){var n={method:"POST",success:c,error:m,params:{ASIN:d.titleId,csrfToken:d.csrfToken,action:b("action"),pageType:d.pageType,subPageType:d.subPageType,dataType:"json"}},h=b("url");a.attr({disabled:!0});var f=b("process");a.val(f);k.log("wl called",h,n);q.ajax(h,n)}}}function p(d,a){a="undefined"!==typeof a?a:d.onWatchlist;return function(b){var n=a?"remove":"add";b=b.charAt(0).toUpperCase()+
b.slice(1);return d[n+b]}}function n(d){a.create({id:d}).show().on("dv:dv-modal:submit",h)}function h(){document.location.reload(!0)}function m(){n("dv-modal-generic-error")}var f=b.$,k=c.create("watchlist-toggle",e),q=d.create("watchlist-call-handler",e);k.log("bound events to",".dv-action-watchlist input:submit");f("body").delegate(".dv-action-watchlist input:submit","click",function(d){d.preventDefault();d=f(d.target);var a=d.data();k.log("initial data",a);a&&a.signInUrl&&""!==a.signInUrl?g.location.href=
a.signInUrl:d.attr("disabled")||l(d,a).callWatchlist()})});e.when("A","jQuery","logging","ready").register("dv-extender",function(b,c,a){var d=a.create("dv-extender",e),l={useEllipsis:!1,resizeDelay:400,hasToggle:!1,hasHiddenToggle:!1,speedQuick:200,maxSpeed:1E3},p=function(a,b){if("undefined"===typeof a)d.error("No element passed to Extender");else return this.elem=a,this.$elem=c(a),this.options=c.extend({},l,b,this.$elem.data("extender")),this};p.prototype={init:function(){"undefined"!==typeof this.$elem&&
(this.$content=this.$elem.find("p"),this.lineHeight=parseInt(this.$content.css("lineHeight"),10),this.originalHeight=this.$elem.height(),this.contentHeight=this.$content.height(),this.seeMoreText=this.options.strings?c("\x3cdiv/\x3e").html(this.options.strings.seeMore).text():"",this.seeLessText=this.options.strings?c("\x3cdiv/\x3e").html(this.options.strings.seeLess).text():"",this.maxOverflowLines="undefined"===typeof this.options.maxOverflowLines?1:this.options.maxOverflowLines,this.isOpen=this.startsOpen=
this.$elem.hasClass("dv-extender-open"),this.speed=this.options.speedQuick+this.contentHeight,this.speed=this.speed>this.options.maxSpeed?this.options.maxSpeed:this.speed,this.ellipsisOnCss={whiteSpace:"nowrap",textOverflow:"ellipsis",overflow:"hidden"},this.ellipsisOffCss={whiteSpace:"normal"},d.info(this),this.extend(),this.attachEvents())},extend:function(){var a=this.ellipsisOffCss,b=this.$elem.height();this.setContentHeight();this.$elem.css({height:b,"max-height":"none"});b=this.contentHeight<=
this.originalHeight+this.maxOverflowLines*this.lineHeight;d.debug("isContentFit",b);b?(this.expandToContentHeight(),this.hideLink()):(this.resetToggle(),this.startsOpen?this.expandToContentHeight():(this.resetOriginalHeight(),this.options.useEllipsis&&(a=this.ellipsisOnCss)),this.showLink());this.$elem.find("p").css(a)},expandToContentHeight:function(){var a=this;d.debug(a.contentHeight);a.$elem.stop().animate({height:a.contentHeight},a.speed,function(){a.$elem.css({height:"auto"})})},attachEvents:function(){var a=
this,b=c("html").hasClass("a-lt-ie9"),m=c(g),f=m.width(),k=!0,e,l;d.debug("isWindowResizeFiredOnElementChange",b);m.resize(function(){b&&(l=m.width(),k=!1,f!==l&&(k=!0,f=l));d.debug("isActualWindowResize",k);clearTimeout(e);e=setTimeout(function(){k&&a.extend()},a.resizeDelay)})},attachClickEvent:function(){var a=this;d.debug(this);a.$extenderAdjustLink&&a.$extenderAdjustLink.click(function(d){d.preventDefault();a.extenderToggle()})},showLink:function(){d.debug("hasToggle",this.options.hasToggle);
this.options.hasToggle?this.$elem.next(".dv-extender-link").show():this.createLink()},createLink:function(){this.$extenderAdjustLink=c("\x3ca\x3e\x3c/a\x3e");this.$extenderAdjustLink.addClass("dv-extender-link "+this.getDefaultLinkClass()).text(this.getDefaultLinkText()).attr("href","#").css({display:"none"}).insertAfter(this.$elem).slideDown(this.options.speedQuick);this.attachClickEvent();this.options.hasToggle=!0},getDefaultLinkClass:function(){d.debug("startsOpen",this.startsOpen);return this.startsOpen?
"dv-extender-see-less":"dv-extender-see-more"},getDefaultLinkText:function(){d.debug("startsOpen",this.startsOpen);return this.startsOpen?this.seeLessText:this.seeMoreText},hideLink:function(){d.debug(this);this.options.hasToggle&&(this.options.hasHiddenToggle=!0,this.resetToggle(),this.$elem.next(".dv-extender-link").hide())},resetOriginalHeight:function(){d.debug(this.originalHeight);this.$elem.stop().animate({height:this.originalHeight},this.speed)},resetToggle:function(){this.changeLink(this.getDefaultLinkText(),
this.getDefaultLinkClass())},setContentHeight:function(){this.$content.css(this.ellipsisOffCss);this.contentHeight=this.$content.height()},extenderToggle:function(){var a=0,b="",c=this.ellipsisOffCss,f=this.seeLessText,k="dv-extender-see-less";this.setContentHeight();this.isOpen=this.$elem.hasClass("dv-extender-open");d.debug(this.isOpen);this.isOpen?(a=this.originalHeight,b="",f=this.seeMoreText,k="dv-extender-see-more",this.options.useEllipsis&&(c=this.ellipsisOnCss)):(a=this.contentHeight,b="dv-extender-open");
this.changeLink(f,k);this.resizeContainer(a,b);this.$elem.find("p").css(c)},resizeContainer:function(a,b){var c=this;d.debug(a,b);c.$elem.removeClass("dv-extender-open").addClass(b).stop().animate({height:a},c.speed,function(){c.isOpen||(c.isOpen=!0,c.$elem.css({height:"auto"}))})},changeLink:function(a,b){var c=this.$elem.next(".dv-extender-link");d.debug(a,b);c.text(a).removeClass("dv-extender-see-more dv-extender-see-less").addClass(b)}};c(".dv-extender").each(function(){(new p(this)).init()});
return p});e.when("A").register("dv-image-loader",function(b){var c=b.$;return function(){var a=new Image;return{loadImageThenExecute:function(b,l){a.src=b;c(a).one("load",l).each(function(){this.complete&&c(this).load()})}}}()});e.when("A","dv-image-loader","ready").register("dv-heroshot",function(b,c){var a=b.$;return function(b,l,e){if(!b)return!1;"undefined"===typeof e&&(e=!0);var g=["aivDetailsBackgroundPanel"];e&&g.push("js-hide-on-play");a("\x3cdiv/\x3e").addClass(g.join(" ")).html("\x3cdiv class\x3d'heroImage'\x3e\x3cdiv class\x3d'aivDetailsGradient'\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e").prependTo(l).each(function(){c.loadImageThenExecute(b,
function(){a(".heroImage").css({display:"none"}).append(a("\x3cimg/\x3e").attr({src:b})).fadeIn(1E3)})})}});e.when("A","dv-heroshot","ready").execute(function(b,c){var a=b.$;(a=a(".dv-heroshot-widget").data("heroshot"))&&c(a,".dp-main")});e.when("jQuery","ready").execute(function(b){b(".dv-load-url-js-win").click(function(c){c.preventDefault();c=parseInt(b(this).data("jsWinHeight"),10)||660;var a=parseInt(b(this).data("jsWinWidth"),10)||680,d=g.screen.width/2-a/2,e=g.screen.height/2-c/2-70;0>d&&(d=
0);0>e&&(e=0);g.open(this.href,"_blank","location\x3dyes,left\x3d"+d+",top\x3d"+e+",width\x3d"+a+",height\x3d"+c)})});"use strict";e.when("A","jQuery","dv-ux","dv-ajax-reload","dv-player-integration","dv-web-player-cfg").register("dp-refresh-handlers",function(b,c,a,d,e,g){function n(){var a=c("#dv-buybox-play a:first").data();null!==a&&"object"===typeof a&&e.prepare({asin:a.asin,trailer:!1,position:a.resumeTime,ref:a.ref,videoType:a.videoType})}function h(a,b,c){return d.getWidgets({asin:a,loggingName:"dvweb-update-playback",
widgets:b,DOMRootID:c})}function m(a){a=a.asin;var b=c("#dv-episode-list").find('[data-aliases*\x3d"'+a+'"]').attr("id");b&&h(a,["js-ajaxable-episode-status"],b)}function f(){a.removeSpinner(c("#dv-action-box-wrapper"))}e.on("closed",function(b){if(b&&!b.trailer){var d=g.get("pageTitleID");d&&(h(d,["dv-action-box"],"dv-action-box-wrapper").then(f).then(n),a.addSpinner(c("#dv-action-box-wrapper")));m(b)}});e.on("asinChanged",m)});"use strict";e.when("A","dv-utils","jQuery").register("dv-trailer-view",
function(b,c,a){function d(){a(f.contentArea).height(l(p().height));a(f.webPlayer).css(p())}function l(b){var d=a(f.actionBox).outerHeight(!0);return Math.max(d,b)+a(f.titleContent).outerHeight(!0)+20}function p(){var b=a(f.actionBox).outerWidth()+20,b=a(f.titleContent).innerWidth()-b;return{width:b,top:a(f.titleContent).outerHeight(!0),left:20,height:Math.min(Math.floor(b/16*9)-20,600)}}function n(){g.navbar&&"function"===typeof g.navbar.lockFlyouts&&g.navbar.lockFlyouts()}function h(){g.navbar&&
"function"===typeof g.navbar.unlockFlyouts&&g.navbar.unlockFlyouts()}function m(a){e.when("navbarJSLoaded").execute(a)}var f={actionBox:"#dv-action-box-wrapper",titleContent:"#dv-dp-title-content",webPlayer:"#dv-web-player",hideDuringPlay:".js-hide-on-play-left",contentArea:".dv-dp-content"},k=c.makeClosure(!1),q;return{open:function(c){m(n);k(!0);q=a(f.contentArea).outerHeight(!0);a(f.hideDuringPlay).animate({opacity:0},c||600,function(){a(f.webPlayer).addClass("trailer-player")});a(f.contentArea).addClass("trailer-view").height(q);
d();b.on.resize(d)},close:function(c){m(h);k(!1);a(f.webPlayer).removeClass("trailer-player").removeAttr("style");a(f.contentArea).height(q);a(f.hideDuringPlay).animate({opacity:1},c||600,function(){a(f.contentArea).removeClass("trailer-view").removeAttr("style")});b.off("resize",d)},calculateContainerHeight:l,getPlayerPosition:p,isPlaying:k.getAccessor()}});e.when("dv-player-integration","dv-player-default-view","dv-trailer-view").execute(function(b,c,a){b.on("play",function(b){e.when("dv-ready-atf").execute(function(){a.isPlaying()&&
a.close();b.trailer&&!b.useFullView?a.open():c.open()})});b.on("closed",function(b){b.trailer&&!b.useFullView?a.close():c.close()})});"use strict";e.when("dv-web-player-cfg","dv-live-incompatable","aiv-modal").register("dv-live-notification",function(b,c,a){c(function(){var d=b.get("strings").liveUnsupportedModal,c=a.create({id:"dv-live-unsupported",content:d.body,header:{text:d.header},buttons:[{type:"submit",text:d.confirm,customEvent:"closeLiveModal"}]});c.on("closeLiveModal",function(){c.remove()});
c.show()})});"use strict";e.when("dv-closure").register("dv-utils",function(b){return{makeClosure:b}});"use strict";e.register("dv-closure",function(){return function(b){function c(b){if("undefined"===typeof b)return a;a=b}var a=b;c.getAccessor=function(){return function(){return a}};return c}});"use strict";e.when("deeplinking","dv-web-player-cfg","purchase-video").execute(function(){"function"===typeof g.setCSMReq&&g.setCSMReq("cf");if("function"===typeof g.uet){g.uet("cf");var b="complete"===document.readyState;
"object"===typeof g.ue&&"function"===typeof g.ue.tag&&g.ue.tag(b?"cf-after-load":"cf-before-load");b&&"function"===typeof g.uex&&g.uex("ld")}});e.when("dv-web-player-csm").execute(function(b){b("dv-detail")})});
/* ******** */
