(function(e){var r=window.AmazonUIPageJS||window.P,t=r._namespace||r.attributeErrors,b=t?t("AmazonVideoUICompatibilityJS"):r;b.guardFatal?b.guardFatal(e)(b,window):b.execute(function(){e(b,window)})})(function(e,r,t){e.when("a-util","a-ajax","a-animate","a-events").register("DVUI",function(b){var g={};b.each(arguments,function(m){b.extend(g,m)});return g});e.when("jQuery","DVUI","logging").register("av-buttons",function(b,g,m){function e(d,c,b){f.debug(c);d.text(c)}function n(d,c,b,a){c&&(d.removeClass([k.confirm,
k.processing].join(" ")),(c=k[c]||"")&&d.addClass(c));b&&e(d,b,a)}function l(d,c){f.log("[addButtonConfirmState]",c,d);d.each(function(d,a){h(b(a));n(b(a),"confirm",c)});b(document).bind("click",a)}function a(){f.log("[resetConfirmButtons]");var d=b("."+k.confirm);d.length&&d.each(p);b(document).unbind("click",a)}function p(d,c){var a=b(c),h=a.data("originalText");n(a,"primary",h,!0)}function h(b){if(!b.data("originalText")){var c=b.text();b.data("originalText",c)}}function v(b){b.length&&b.each(p)}
var f=m.create("av-button"),k={confirm:"av-button--confirm",processing:"js-button-processing av-button--processing"};b("body").delegate("[data-state-confirm-text]","click",function(a){var c=b(a.currentTarget),h=c.attr("id");c.hasClass(k.processing)?(f.log("processing state"),a.preventDefault(),a.stopImmediatePropagation()):c.hasClass(k.confirm)?(f.log("confirm state, id",h),v(c),h&&(c=["av-confirm-button",h,"confirmed"].join(":"),f.log(h,c),g.trigger(c,a))):(f.log("initial state"),a.preventDefault(),
a.stopImmediatePropagation(),l(c,c.data("stateConfirmText")))});return{buttonContent:e,buttonState:n,applyProcessingState:function(a,c){f.log("[addButtonProcessingState]");a.each(function(a,d){h(b(d));n(b(d),"processing",c)})},applyConfirmState:l,resetButtonsOriginalState:v,resetConfirmButtons:a}});e.when("jQuery").register("av-form",function(b){return{submit:function(g,e,q){b.ajax({url:g.action,type:"POST",data:b(g).serialize(),success:function(b){e(b)},error:function(b){q(b)}})}}});"use strict";
e.when("jQuery","DVUI","logging","A").register("av-sticky-section",function(b,g,m,q){function n(a){d=b("#av-sticky-placeholder");w=b(".js-sticky-placeholder-container");c=b("#av-sticky-section");z=b("body");var f=c.find(".av-sticky-content-wrapper");f.length&&f.each(function(){var a=b(this),c="av-sticky-"+ ++t;x[c]=new y(a,c)});k.debug("init",a);u=b.extend({},A,a);c.length||(c=b("\x3cdiv /\x3e").addClass("av-sticky-section").attr({id:"av-sticky-section"}).prependTo(z));d.length||(p(),g.on("resize",
h),l());h()}function l(){var b=a();0>b&&c.css({top:b});c.addClass("av-stuck");g.delay(function(){c.removeAttr("style")},10)}function a(){var a=b("html").offset();if(0<=a)return 0;var d=c.offset(),h=c.height(),a=d.top+a.top;return a<-1*h?h:a}function p(){var a=w&&w.length?w:z;d=b("\x3cdiv /\x3e").attr({id:"av-sticky-placeholder"}).prependTo(a)}function h(a){if("undefined"===typeof a||"object"===typeof a)a=c.outerHeight();g.animate(d,{height:a},u.speed)}function v(a){return(a=a.data("stickyId"))&&x[a]}
function f(a){c.append(a);h();a.css({display:"none"});g.slideDown(a,u.speed)}var k=m.create("av-sticky-section",e),d,c,z,w,u,t=0,x={},A={speed:300,flashMessageDelay:4E3},y=function(a,b){this.$el=a;this.id=b};y.prototype.remove=function(a){var b=this.$el,d=this.id,f=this.delayHandler,p=b.height(),k=c.height();1>b.length||(g.slideUp(b,u.speed,"",function(){b.remove();delete x[d];"function"===typeof a&&a()}),h(k-p),f&&r.clearTimeout(f))};b("body").delegate(".js-dismissible-close","click",function(a){k.debug("dismissible click");
a.stopPropagation();a.preventDefault();a=b(this).closest(".av-sticky-content-wrapper");a=v(a);var c=b(this).closest(".av-dismissible");a?a.remove():(new y(c)).remove();q.trigger("dv-dismissible-closed",c.attr("id"))});return{init:n,makeItStick:l,addContent:function(a,d){var h=b("\x3cdiv /\x3e"),p=d||{},e="av-sticky-"+ ++t,m,l,q;k.debug(a);n(u);h.addClass("av-sticky-content-wrapper").attr("data-sticky-id",e).html(a);p.dedupeId&&(h.attr("data-sticky-dedupe-id",p.dedupeId),m=c.find(['[data-sticky-dedupe-id\x3d"',
p.dedupeId,'"]'].join("")));m&&m.length&&(q=v(m));l=new y(h,e);x[e]=l;p.isFlashMessage&&(l.delayHandler=g.delay(function(){l.remove();k.debug("[flashMessage] delay")},u.flashMessageDelay));q?q.remove(function(){f(h)}):f(h);return l}}});e.when("av-sticky-section","av-sticky-section-rendered").execute(function(b){b.init()});e.when("jQuery","logging","av-ui-templates-ready").register("av-ui-templates",function(b,g){var m=g.create("av-templates",e);return{get:function(e){var g=b("#av-tmpl-"+e).html();
m.debug("widget template: ",e,JSON.stringify(g));return g.trim()}}});e.when("jQuery","logging","av-sticky-section","av-ui-templates-ready").register("av-alerts",function(b,e,m){function q(a,b){if(0===a.length)l.error("_addContent missing $template",arguments);else return void 0!==b.selector&&(b=b.html()),a.find(".av-alert-content").html(b).end()[0].outerHTML}function n(a,e,h){var g=e||{};if(a){l.debug(a,g,h);var f;f=a;var k=g.format,d=h;"undefined"===typeof k&&(k="block");"undefined"===typeof d&&
(d="info");k=["av-tmpl",d,k].join("-");d=b("#"+k).html();l.debug("_getAlert",k,d,f);f=q(b(d),f);return m.addContent(f,g)}l.error("missing content",arguments)}var l=e.create("av-alerts");return{info:function(a,b){return n(a,b,"info")},warning:function(a,b){return n(a,b,"warning")},error:function(a,b){return n(a,b,"error")},success:function(a,b){return n(a,b,"success")}}});e.when("jQuery","logging","DVUI","av-ui-templates").register("watchlist-toggle",function(b,g,m,q){function n(b){function e(d){var c=
d&&"added"===d.status?!0:!1;1===d.success?(f=l(a,c),b.data({onWatchlist:c})):document.location.reload();var n=f("initial");b.html(n.replace(/\{lineBreak\}/,'\x3cspan class\x3d"dv-conditional-linebreak"\x3e\x3cbr\x3e\x3c/span\x3e')).removeAttr("style");clearTimeout(g);b.attr({disabled:!1,"data-on-watchlist":c});m.trigger("watchlist-box-success",c?"add":"remove",a.titleId);p.log("recieved wl response",d)}a=b.data();var f=l(a),g;p.log("initial data",a);return{callWatchlist:function(){if(a&&a.signInUrl&&
""!==a.signInUrl)r.location.href=a.signInUrl;else{b.attr({disabled:!0});g=m.delay(function(){var a=q.get("fill-spinner");b.css({width:b.outerWidth(),height:b.outerHeight(),display:"block"}).html(a)},350);var d={method:"POST",success:e,error:document.location.reload,params:{itemId:a.titleId,csrfToken:a.csrfToken,action:f("action"),pageType:a.pageType,subPageType:a.subPageType,dataType:"json"}},c=f("url");p.log("wl called",c,d);m.ajax(c,d)}}}}function l(a,b){b="undefined"!==typeof b?b:a.onWatchlist;
return function(f){var e=b?"remove":"add";f=f.charAt(0).toUpperCase()+f.slice(1);return a[e+f]}}var a,p=g.create("watchlist-toggle",e);p.log("bound events to",".js-action-watchlist");b("body").delegate(".js-action-watchlist","click",function(a){a.preventDefault();a=b(a.target);a.attr("disabled")||n(a).callWatchlist()})})});
/* ******** */
(function(b){var f=window.AmazonUIPageJS||window.P,h=f._namespace||f.attributeErrors,a=h?h("AmazonVideoUICompatibilityAssets"):f;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,f,h){b.when("A","DVUI").execute(function(a,c){a.on("dv-dismissible-closed",function(a){void 0!==a&&c.ajax("https://"+document.location.hostname+"/alert",{method:"POST",params:{type:"dismissible",id:a}})})});b.when("jQuery","CSContactUSWidgetJS","av-contact-us-widget").execute(function(a,
c,b){var g=function(a){var e="";if(a&&a.issueIdentifierMap&&a.issueDescriptionMap)for(var b=["firstNode","secondNode","thirdNode","fourthNode"],d=0;d<b.length;d++){var k=b[d],c=a.issueIdentifierMap[k];if(c)0<d&&(e+=":::"),e+=c,e+="::"+a.issueDescriptionMap[k];else break}return e};c=JSON.parse(b.get("options"));c.phoneOptions.initiateTrustedCallCallback=function(b,e,c){var d={};b={ie:"UTF8",c2cId:b.options.c2cId,callContextId:"",callAfterMins:c.callAfterMins,userCallbackNumber:JSON.stringify(e),virtualCall:c.virtualCall,
clientSessionId:b.options.clientSessionId,screenShareRequested:0,customerSelectedIssues:g(b.options.customerSelectedIssueCodeInfo)};a.ajax({async:!1,cache:!1,contentType:"application/x-www-form-urlencoded; charset\x3dutf-8",url:"/gp/video/help/ajax/initiate-call.html",data:b,dataType:"json",success:function(a){a&&(d=a)},error:function(a){d=a}});return d};c.phoneOptions.errorCallback=function(b){a.ajax({cache:!1,type:"POST",url:"/gp/video/help/ajax/log-error.html",data:{msg:"C2CJSError: "+b,type:"Click2Call"}})};
a("#av-contactus-widget").amznContactUsDesktopFlow(c)});b.when("jQuery","CSContactUSWidgetJS","av-chat-widget").execute(function(a,b,f){var g=JSON.parse(f.get("options"));g.initiateTrustedChatCallback=function(b,c,f){var d=null;b=JSON.stringify({name:b||"",email:f||"",initialQuestion:c||""});a.ajax({async:!1,cache:!1,url:"/gp/video/help/ajax/initiate-chat.html",data:{c2cId:g.chatTemplateId,userInfo:b},dataType:"json",success:function(a){d=a},error:function(a){d=a}});return d};a("#av-chat-widget").amznChatCustomerFlow(g)})});
/* ******** */
