(function(q){var l=window.AmazonUIPageJS||window.P,r=l._namespace||l.attributeErrors,m=r?r("DigitalVideoWebHoverAssets"):l;m.guardFatal?m.guardFatal(q)(m,window):m.execute(function(){q(m,window)})})(function(q,l,r){q.when("A","hoverPositionCalculator","ready").register("av-hover",function(m,p){var h=m.$,k,a,c=null,b=null,d=l.uet,f=l.ues,e=l.uex,u=l.ue,g=function(a){return{afCalled:!1,recordEvent:function(c){"object"===typeof u&&"function"===typeof f&&"function"===typeof d&&"function"===typeof e&&
a&&("t0"===c?f(c,a,new Date):"spinner"===c?u.count(a+":spinner",1):"ld"===c?e(c,a,{wb:1}):"af"===c?this.afCalled||(this.afCalled=!0,d(c,a,{wb:1})):d(c,a,{wb:1}))}}},n={hideTimer:null,titleID:null,finalPositionSet:!1,chunkHandler:function(a){(!a||a.length)&&"hover-body"===a[0]&&b&&b.append(h(a[1]))},getDefaultAllowedArea:function(){var a=h(l);h(".a-section.dv-standard-carousel .dv-carousel, #aiv-cl-main-middle").first();var c=a.scrollTop(),b=a.scrollTop()+a.height(),d=a.scrollLeft(),a=a.scrollLeft()+
a.width();return{top:c,left:d,bottom:b,right:a}},getSkin:function(a){return'\x3csection id\x3d"av-hover" class\x3d"avu-content av-narrow"\x3e\x3cdiv class\x3d"av-hover-theme-container av-hover '+(a?"avu-section-alt":"avu-section av-popover")+'"\x3e\x3cspan id\x3d"arrow-hover"\x3e\x3cspan id\x3d"arrow"\x3e\x3c/span\x3e\x3c/span\x3e\x3cdiv class\x3d"av-spinner"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/section\x3e'},setPosition:function(a,c){if(!this.finalPositionSet){var b=h(".av-hover"),d=b.find("#arrow-hover"),
f=d.find("#arrow"),e=b.find(".av-spinner");if(b.length&&f.length){e.css({"margin-top":80,"margin-bottom":80});var e=c||this.getDefaultAllowedArea(),g=a.offset,g={top:g.top,left:g.left,bottom:g.top+a.height,right:g.left+a.width,height:a.height,width:a.width},k={height:b.outerHeight(),width:b.outerWidth()},e=p.calculatePosition(g,k,e),g=p.calculateArrowPosition(g,{top:e.hoverPosition.top,left:e.hoverPosition.left,width:k.width,height:k.height},e.orientation,{height:12,base:16},b.css("border-width"));
b.css(e.hoverPosition).removeClass("av-hover-top").removeClass("av-hover-left").removeClass("av-hover-right").removeClass("av-hover-bottom").addClass("av-hover-"+e.orientation).fadeIn();d.css(g.arrowHoverPosition);f.css(g.arrowPosition).removeClass("arrow-top").removeClass("arrow-left").removeClass("arrow-right").removeClass("arrow-bottom").addClass(g.arrowClass).fadeIn()}else this.hideImediately()}},show:function(d){var e=this,f=null,u=d.titleId,n=d.trigger,p=d.relatedRequestId,q=d.type,r=d.refTag,
v=d.LCID,w=d.whyReasons,x=d.allowedArea,t=g("dv-av-hover"+(q?"downloadable_movie"===q?"-movie":"-tv":"-unknown"));h("#av-hover").length&&u===e.titleID||(h("#av-hover").length&&e.hideImediately(),clearTimeout(k),clearTimeout(a),null!==e.hideTimer&&clearTimeout(e.hideTimer),c&&c.abort(),e.finalPositionSet=!1,b=h("body"),b.append(e.getSkin(d.altTheme||!1)),k=setTimeout(function(){t.recordEvent("t0");t.recordEvent("bb");var b={format:"json",refTag:r};w&&(b.whyReasons=w);v&&(b.LCID=v);p&&(b.relatedRequestId=
p);var d=l.location.pathname,g="/gp/video/hover/";d.match(/\/region\//)&&(g=d.replace(/(\/region\/\w{2})(.*?)+$/,"$1/gp/video/hover/"));g+=u;a=setTimeout(function(){e.setPosition(n,x);t.recordEvent("spinner");t.recordEvent("af")},400);c=m.ajax(g,{method:"get",params:b,accepts:"application/json-amazonui-streaming",timeout:1E4,chunk:e.chunkHandler,success:function(c){f=h("#av-hover-body").html();h("#av-hover-body").remove();h(".av-spinner").remove();h(".av-hover-theme-container").append(f);e.titleID=
u;e.setPosition(n,x);e.finalPositionSet=!0;clearTimeout(a);t.recordEvent("af");t.recordEvent("cf");t.recordEvent("ld")},error:function(){e.hideImediately()}})},20))},hide:function(){clearTimeout(k);var a=this;a.hideTimer=setTimeout(function(){a.hideImediately();clearTimeout(a.hideTimer)},200)},hideImediately:function(){clearTimeout(k);c&&(c.abort(),c=null);n.titleID=null;h("#av-hover").remove();h("#av-hover").stop(!0,!0).hide()}};h("#av-hover").live("mouseenter",function(a){null!==n.hideTimer&&clearTimeout(n.hideTimer)}).live("mouseleave",
function(a){n.hideImediately()});h("a.why-recommend-link").live("click",function(a){a.preventDefault();a=h(this).attr("href");var c=l.innerHeight,b=Math.round(l.innerWidth/2-275),c=Math.round(.3*c);l.open(a,"whyRecommended",["height\x3d450,width\x3d550","left\x3d"+b,"top\x3d"+c,"menubar\x3d0,scrollbars\x3d1,toolbar\x3d0,status\x3d0"].join())});return n});q.register("hoverPositionCalculator",function(){function m(c){switch(c){case a.HoverOrientationTypes.Right:case a.HoverOrientationTypes.Left:return!0;
case a.HoverOrientationTypes.Top:case a.HoverOrientationTypes.Bottom:return!1;default:throw"CalculateArrowPosition - Orientation value not expected: "+c;}}function p(a,b,d){var f=Math.min(d?a.top+a.height:a.left+a.width,d?b.top+b.height:b.left+b.width);a=Math.max(d?a.top:a.left,d?b.top:b.left);return f-a}function h(a,b,d,f){var e=p(a,b,m(d));a=m(d)?Math.max(0,a.top-b.top):Math.max(0,a.left-b.left);return(e-f)/2+a}function k(c,b,d,f){var e;switch(c){case a.AxisTypes.Horizontal:e=b===a.HoverOrientationTypes.Right&&
d.right>=f.width||b===a.HoverOrientationTypes.Left&&d.left>=f.width?b:d.bottom>=.9*f.height?a.HoverOrientationTypes.Bottom:d.top>=f.height-a.hoverPaddingTop?a.HoverOrientationTypes.Top:d.bottom>=.7*f.height?a.HoverOrientationTypes.Bottom:d.right>=.7*f.width?a.HoverOrientationTypes.Right:d.left>=.85*f.width?a.HoverOrientationTypes.Left:d.right/f.width>=d.bottom/f.height?a.HoverOrientationTypes.Right:a.HoverOrientationTypes.Bottom;break;case a.AxisTypes.Vertical:e=b===a.HoverOrientationTypes.Bottom&&
d.bottom>=f.height||b===a.HoverOrientationTypes.Top&&d.top>=f.height?b:d.right>=.7*f.width?a.HoverOrientationTypes.Right:d.left>=.85*f.width?a.HoverOrientationTypes.Left:d.bottom>=.9*f.height?a.HoverOrientationTypes.Bottom:d.top>=f.height-a.hoverPaddingTop?a.HoverOrientationTypes.Top:d.bottom>=.7*f.height?a.HoverOrientationTypes.Bottom:d.right/f.width>=d.bottom/f.height?a.HoverOrientationTypes.Right:a.HoverOrientationTypes.Bottom}return e}var a={hoverPaddingTop:26,HoverOrientationTypes:{Top:"top",
Bottom:"bottom",Left:"left",Right:"right"},AxisTypes:{Horizontal:"Horizontal",Vertical:"Vertical"},PackshotPlacementTypes:{WithinBounds:"WithinBounds",OutOfBoundsTop:"OutOfBoundsTop",OutOfBoundsBottom:"OutOfBoundsBottom",OutOfBoundsLeft:"OutOfBoundsLeft",OutOfBoundsRight:"OutOfBoundsRight"}};return{computeIntersections:p,calculatePosition:function(c,b,d,f){var e,h,g;if(void 0===c||void 0===b||void 0===d)return{};c.bottom=c.bottom||c.top+c.height;c.right=c.right||c.left+c.width;e=0>c.left-d.left?a.PackshotPlacementTypes.OutOfBoundsLeft:
0>d.right-c.right?a.PackshotPlacementTypes.OutOfBoundsRight:a.PackshotPlacementTypes.WithinBounds;h=0>c.top-d.top?a.PackshotPlacementTypes.OutOfBoundsTop:0>d.bottom-c.bottom?a.PackshotPlacementTypes.OutOfBoundsBottom:a.PackshotPlacementTypes.WithinBounds;g={top:c.top-d.top,left:c.left-d.left,bottom:d.bottom-c.bottom,right:d.right-c.right};var n=g.right>=g.left?a.HoverOrientationTypes.Right:a.HoverOrientationTypes.Left,m=g.bottom>=g.top?a.HoverOrientationTypes.Bottom:a.HoverOrientationTypes.Top;if(h===
a.PackshotPlacementTypes.WithinBounds)e=n===a.HoverOrientationTypes.Right&&g.right>=b.width||n===a.HoverOrientationTypes.Left&&g.left>=b.width?n:k(a.AxisTypes.Vertical,m,g,b);else if(e===a.PackshotPlacementTypes.WithinBounds)e=m===a.HoverOrientationTypes.Bottom&&g.bottom>=b.height||m===a.HoverOrientationTypes.Top&&g.top>=b.height?m:k(a.AxisTypes.Horizontal,n,g,b);else{var l;h===a.PackshotPlacementTypes.OutOfBoundsTop?e===a.PackshotPlacementTypes.OutOfBoundsLeft?l=c.right-d.left>c.bottom-d.top?k(a.AxisTypes.Vertical,
a.HoverOrientationTypes.Bottom,g,b):k(a.AxisTypes.Horizontal,a.HoverOrientationTypes.Right,g,b):e===a.PackshotPlacementTypes.OutOfBoundsRight&&(l=d.right-c.left>c.bottom-d.top?k(a.AxisTypes.Vertical,a.HoverOrientationTypes.Bottom,g,b):k(a.AxisTypes.Horizontal,a.HoverOrientationTypes.Left,g,b)):h===a.PackshotPlacementTypes.OutOfBoundsBottom&&(l=e===a.PackshotPlacementTypes.OutOfBoundsLeft?c.right-d.left>d.bottom-c.top?k(a.AxisTypes.Vertical,a.HoverOrientationTypes.Top,g,b):k(a.AxisTypes.Horizontal,
a.HoverOrientationTypes.Right,g,b):d.right-c.left>d.bottom-c.top?k(a.AxisTypes.Vertical,a.HoverOrientationTypes.Top,g,b):k(a.AxisTypes.Horizontal,a.HoverOrientationTypes.Left,g,b));e=l}a:switch(e){case a.HoverOrientationTypes.Right:h=c.right;g=c.top-a.hoverPaddingTop;break a;case a.HoverOrientationTypes.Left:h=c.left-b.width;g=c.top-a.hoverPaddingTop;break a;case a.HoverOrientationTypes.Top:h=c.left+(c.width-b.width)/2;g=c.top-b.height;break a;case a.HoverOrientationTypes.Bottom:h=c.left+(c.width-
b.width)/2;g=c.bottom;break a;default:throw"GetHoverPosition - Orientation value not expected: "+e;}b.left=h;b.top=g;if(void 0===d||void 0===c||void 0===b||e!==a.HoverOrientationTypes.Left&&e!==a.HoverOrientationTypes.Right&&e!==a.HoverOrientationTypes.Top&&e!==a.HoverOrientationTypes.Bottom)c={};else{switch(e){case a.HoverOrientationTypes.Right:case a.HoverOrientationTypes.Left:b.top=Math.min(b.top,d.bottom-b.height);b.top=Math.max(b.top,d.top);c.top-a.hoverPaddingTop>b.top&&d.top<b.top&&c.top+c.height<
b.top+b.height&&(b.top=Math.max(d.top,b.top-(b.top+b.height-(c.top+c.height))));break;case a.HoverOrientationTypes.Top:case a.HoverOrientationTypes.Bottom:b.orientation===a.HoverOrientationTypes.Top&&(b.top=Math.min(b.top,c.top-b.height)),b.left=Math.min(b.left,d.right-b.width),b.left=Math.max(b.left,d.left)}c={left:b.left,top:b.top}}if(f)switch(e){case a.HoverOrientationTypes.Right:c.left+=f;break;case a.HoverOrientationTypes.Left:c.left-=f;break;case a.HoverOrientationTypes.Top:c.top-=f;break;case a.HoverOrientationTypes.Bottom:c.top+=
f}return{hoverPosition:c,orientation:e}},calculateArrowPosition:function(c,b,d,f,e){if(void 0===c||void 0===b||d!==a.HoverOrientationTypes.Left&&d!==a.HoverOrientationTypes.Right&&d!==a.HoverOrientationTypes.Top&&d!==a.HoverOrientationTypes.Bottom||"undefined"===typeof f)return{};e=e?2*l.parseFloat(e):0;var k=0,g=0,n,p,q=0,r=0;m(d)?(p=b.height,n=f.height,g=h(c,b,d,f.base)):(n=b.width,p=f.height,k=h(c,b,d,f.base));switch(d){case a.HoverOrientationTypes.Right:c="arrow-left";q=-1*f.height;break;case a.HoverOrientationTypes.Left:c=
"arrow-right";q=b.width-e;break;case a.HoverOrientationTypes.Top:c="arrow-bottom";r=b.height-e;break;case a.HoverOrientationTypes.Bottom:c="arrow-top";r=-1*f.height;break;default:throw"CalculateArrowPosition - Orientation value not expected: "+d;}return{arrowPosition:{left:k,top:g},arrowHoverPosition:{left:q,top:r,width:n,height:p},arrowClass:c}}}});q.when("A","av-hover","ready").register("hover-dom",function(m,l){var h=m.$;return{init:function(k,a,c){h(k).live("mouseenter",function(b){var d=h(this);
if(!a||"function"!==typeof a||a(d)){b=0<d.parents(".avu-section-alt").length;var f=c&&"function"===typeof c?c():null;b={trigger:{offset:d.offset(),width:d.outerWidth(),height:d.outerHeight()},titleId:d.data("titleId")||d.data("asin"),LCID:d.data("lcid"),refTag:"dv-hover",type:d.data("type"),shouldHideWhenMouseLeave:function(a){return d!==a&&0>h(a).parents().index(d)},relatedRequestId:h("#pageData").attr("data-request"),altTheme:b,allowedArea:f,whyReasons:d.data("why-reasons")};l.show(b)}}).live("mouseleave click",
function(a){h(a.relatedTarget).is("#av-hover")||h(a.relatedTarget).is("#arrow-hover")||l.hide()})}}});q.when("A","hover-dom","ready").execute(function(m,p){function h(a){return a.closest(".dv-standard-carousel").hasClass("dv-list-remove-item-highlight-selected")?!1:!0}function k(){var c=a(l),b=a("#av-nav.av-nav.av-blur-backdrop").outerHeight()||0,d=a(".a-section.dv-standard-carousel .dv-carousel, #aiv-cl-main-middle").first();return allowedArea={top:c.scrollTop()+b,bottom:c.scrollTop()+c.height(),
left:d.offset().left,right:d.outerWidth()}}var a=m.$;p.init(".dark-hover-enabled",h,k);p.init(".dv-universal-hover-enabled",h,k)})});