(function(k){var n=window.AmazonUIPageJS||window.P,t=n._namespace||n.attributeErrors,b=t?t("CustomerReviewsCommonAssets"):n;b.guardFatal?b.guardFatal(k)(b,window):b.execute(function(){k(b,window)})})(function(k,n,t){k.when("A","cr-log-utils","cr-uri-utils").register("cr-ajax-model",function(b,a,c){function d(a){var b=c.getUrlParametersMap()||{};b["overrides-marketplace-id"]&&(a=c.addKeyValuePair(a,"overrides-marketplace-id",b["overrides-marketplace-id"]));return a}function f(a){m[a]&&(m[a].abort(),
delete m[a])}function h(c,u,r,q,k,t,D){var C;C=t?t:p=p++;t=C;k=k?k:u.error||function(){};q=q?q:0;r=r?r:3;var z=u.finallyCallback||function(){};c=d(c);D||(D="reviewsAjax"+e++,n.uet&&n.uet("tc",D));u.params.scope=D;u.contentType="application/x-www-form-urlencoded;charset=UTF-8";var v=u.success||function(){};u.success=function(a){delete m[t];"function"===typeof v&&v(a);"function"===typeof z&&z(a)};u.error=function(b){f(t);q++;q<r?(a.logError("AJAX Post to "+c+" failed, Attempt: "+q+" out of "+r,"WARN"),
h(c,u,r,q,k,t,D)):(a.logError("AJAX Post to "+c+" from "+n.location.href+" failed, exhausted "+r+" attempts","FATAL"),"function"===typeof k&&k(b),"function"===typeof z&&z(b))};m[t]=b.post(c,u);return t}var e=0,p=1,m={};return{abort:f,post:h}});k.when("A","jQuery","cr-log-utils").register("cr-A",function(b,a,c){var d={top:-100,left:-100};b.inView=function(b){b=b||a();if("function"===typeof b.offset){var c=(b.offset()||d).top-a(n).scrollTop();b=0<=c;c=c<a(n).height();return b&&c}return!1};
b.compositeEventWrapper=function(a,d,e){var p=a;e&&(p=b.throttle(p,e,{trailing:!1}));return c.jsGuard(function(a){a&&(p(a),d&&a.$event&&a.$event.preventDefault())})};b.onScreenAndVisible=function(){b.onScreen.apply(this,arguments)};return b});k.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",
UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",
SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",FILTER_APPLY:"reviews:filter-action:apply",FILTER_APPLY_BEGIN:"reviews:filter-action:apply-begin",FILTER_APPLY_SUCCESS:"reviews:filter-action:apply-success",FILTER_APPLY_ERROR:"reviews:filter-action:apply-error",FILTER_APPLY_DONE:"reviews:filter-action:apply-done",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",
SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",SELECT_PRODUCT_LINK:"reviews:select-product-link",FEEDBACK_CLICK:"reviews:skyfall-feedback-click",CLIQUE_CLICK:"reviews:skyfall-clique-click",STAR_RATING_CLICK:"ryp:star-rating-click",
STAR_RATING_CLEAR:"ryp:star-rating-clear-click"},filterOptions:{SORT_KEY:"sortBy",HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",
AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews",MEDIA_KEY:"mediaType",ALL_CONTENTS:"all_contents",MEDIA_ONLY:"media_reviews_only"},keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}});k.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(b,a,c){function d(d){var h={};d&&d.data&&(h=d.data);var e=a.defaultIfBlank(h.url,d.$target.find("a").andSelf().filter("a").attr("href")),p=a.defaultIfBlank(h.title,
"CustomerReviews"),p=""+p,m="";b.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(b,c){var d=a.defaultIfBlank(h[c],b);m+=c+"="+d+","});var m=m.slice(0,-1),g=null;try{(g=n.open(e,p,m))?g.focus():c.logError("Unable to move focus to popup window with data: "+a.stringify(h),"ERROR"),d.$event.preventDefault()}catch(u){c.logError("Unable to open window with parameters: "+a.stringify(h),"FATAL",u)}return g}b.declarative("cr-popup",["click"],c.jsGuard(d));return{popup:d}});
k.when("A","jQuery","reviews-constants").register("cr-generic-declarative-actions",function(b,a,c){function d(b){b&&b.data&&b.data.selector&&b.data.cssClass&&b.$event&&"function"===typeof b.$event.preventDefault&&(a(b.data.selector).toggleClass(b.data.cssClass),b.$event.preventDefault())}b.declarative(c.events.TOGGLE_CLASS_CLICK,"click",d);return{toggleCssClass:d}});k.when("A","ready").register("cr-global-model",function(b){var a=b.state("reviews-page-state");a||(a=b.$("#cr-state-object").data("state"));
var c=null;a&&(c=a.customerId);return{generateUrl:function(a,b){var c=a;c&&"/"!==c.charAt(c.length-1)&&(c+="/");c&&b&&(c=c+"ref="+b);return c},isSignedIn:function(){return c?!0:!1}}});k.when("A","a-expander","jQuery","reviews-constants","cr-string-utils").register("cr-global-view",function(b,a,c,d,f){function h(a){var b="";if(a&&a.closest!==t){var c=a.closest("*["+u.REFTAG+"]");c&&(b=c.attr(u.REFTAG))}f.isBlank(b)&&a&&a.closest!==t&&(a=a.closest("*[rel]"))&&(b=a.attr("rel"));return f.defaultIfBlank(b,
"cm_cr_unknown")}function e(a){return a&&"function"===typeof a.is?a.is("*["+u.getReviews.CHECKED+"]")&&a.is("*["+u.getReviews.UNCHECKED+"]"):!1}function p(a){return a&&a.has!==t&&a.is!==t?0<a.find(":checked").length||a.is(":checked"):!1}function m(a,b){return a&&a.attr!==t&&b?f.parseJSON(a.attr(b))||{}:{}}function g(a){return a!==t}var u=d.data;b.on("a:expander:review_text_read_more:toggle:collapse",function(a){g(a)&&g(a.expander)&&g(a.expander.$expander)&&1===a.expander.$expander.length&&g(a.expander.$expander[0].closest(".review"))&&
g(a.expander.$expander[0].closest(".review").offsetTop)&&(a=a.expander.$expander[0].closest(".review").offsetTop,n.scroll(0,a))});b.on("a:pageUpdate",function(){g(a)&&a.initializeExpanders()});return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(u.getReviews,function(a,b){return a+"*["+b+"],"},"").slice(0,-1),d;c&&a&&a.closest!==t&&(d=a.closest(c));return e(d)?p(d)?m(d,u.getReviews.CHECKED):m(d,u.getReviews.UNCHECKED):m(d,u.getReviews.STANDARD)},getReftag:function(a){var b;a&&a.$target&&
(b=a.$target);a&&a.id&&(b=c("#"+a.id));a&&a.expander&&a.expander.$expander&&(b=a.expander.$expander);b=h(b);"cm_cr_unknown"===b&&a&&a.data&&a.data.reftag&&(b=a.data.reftag);return b},getReftagByDom:h,scrollTo:function(a,b){var d=c(a).offset(),e=b||0,g=c("#cr-state-object").data("state"),g=g!==t&&g.disableScroll;d&&d.top!==t&&!g&&(c("html,body").stop(),c("html,body").animate({scrollTop:d.top-e},{queue:!1,duration:500}))}}});k.when("A").register("cr-log-utils",function(b){function a(a,
b,c){n.ueLogError&&("string"!==typeof b&&(b="FATAL"),c?n.ueLogError(c,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):n.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function c(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:a,jsGuard:function(b){if("function"===typeof b)return function(){try{return b.apply(this,arguments)}catch(c){a("Uncaught Error in function","FATAL",c)}};a("Unable to wrap non-function","ERROR");
return b},incrementCount:function(a,b){if(n.ue){var h=c(a,b),e=n.ue.count(h)||0;n.ue.count(h,e+1)}},logCount:function(a,b,h){n.ue&&(a=c(a,h),n.ue.count(a,b))}}});k.register("cr-mash-utils",function(){var b=!1;k.when("mash").execute(function(){b=!0});return{isMash:function(){return b}}});k.when("A","cr-log-utils").register("cr-number-utils",function(b,a){return{convertToInteger:function(b,d){if(b===parseInt(b,10))return b;if(null!==b&&b!==t&&""!==b)return parseInt(b.replace(/[^0-9]/g,
""),10);if(d!==t)return d;a.logError("convertToInteger","Cannot convert "+b+" to Integer");return 0}}});k.when("cr-A","jQuery","cr-string-utils","afterReady").register("cr-on-view-utils",function(b,a,c){function d(a,c){if(!e[a]){var d=f(a,c)();p[a]=(p[a]||[]).concat(d);b.on.scroll(d)}}function f(c,d){return function r(){b.inView(a(c))&&(h(c,d),b.each(p[c]||[],function(a){b.off("scroll",a)}));return r}}function h(a,c){e[a]||(e[a]=!0,b.post(c.ajaxUrl,{params:c.ajaxParamsMap||{}}))}var e=
{},p={};b.each(a("*[data-cr-trigger-on-view]"),function(b,e){var f=a(b),h=f.attr("data-cr-trigger-on-view"),h=c.parseJSON(h);if(null!==h){var p="cr-trigger-on-view-"+e;f.addClass(p);d("."+p,h)}});return{triggerOnScrollIntoView:d,trigger:h}});k.when("A","jQuery").register("cr-streaming-utils",function(b,a){return{appendFadeIn:function(c){if(null!==c&&2<c.length&&null!==c[1]&&null!==c[2]){var d=c[1];c=a(c[2]).hide();a(d).append(c);b.fadeIn(c,500,"ease-in-out",function(){})}}}});
k.when("A","cr-log-utils").register("cr-string-utils",function(b,a){function c(a){return null===a||a===t?!0:0===b.trim(a).length}return{defaultIfBlank:function(a,b){return c(a)?b:a},isBlank:c,parseJSON:function(c){try{return b.parseJSON(c)}catch(f){a.logError("Unable to parse JSON object","ERROR",f)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},stringify:function(a){return n.JSON&&n.JSON.stringify?n.JSON.stringify(a):a}}});k.when("A").register("cr-uri-utils",
function(b){function a(a){a=a||n.location.href;var d={},f=a.indexOf("?"),h=a.indexOf("#");a=a.slice(f+1,h>f?h:t)||"";f=[];-1<a.indexOf("&")?f=a.split("&"):-1<a.indexOf("=")&&(f=[a]);b.each(f,function(a,b){if(0<a.indexOf("=")){var c=a.split("=");d[c[0]]=c[1]}});return d}return{getUrlParametersMap:a,addKeyValuePair:function(b,d,f){f=f||0;if(a(b)[d]===f||!b||!d)return b;d="?"+d+"="+f;return-1<b.indexOf("?")?b.replace("?",d+"&"):b+d}}});k.when("A","cr-uri-utils","cr-string-utils","3p-urijs").register("cr-extended-uri-utils",
function(b,a,c,d){function f(){return d(n.location.href)}function h(){return f().query()}return b.$.extend(a,{getCurrentUri:f,getCurrentQueryString:h,getCurrentQueryParameters:function(){return d.parseQuery(h())},isAmazonDomain:function(a){if("string"===typeof a||a instanceof String)a=d(a);var b=c.startsWith(a.domain(),"amazon");!1===b&&(a=a.hostname(),a=a.substring(a.indexOf(".")+1),b=c.startsWith(a,"amazon"));return b},setQueryParameters:function(a,f){if("string"===typeof a||a instanceof String)a=
d(a);b.each(f,function(b,d){c.isBlank(b)?a.removeSearch(d):a=a.setSearch(d,b)});return a},setReftag:function(a,b){if("string"===typeof a||a instanceof String)a=d(a);for(var f=a.segment(),g=!1,h=f.length-1;0<=h;h--)if(c.startsWith(f[h],"ref=")){g=!0;f[h]="ref="+b;break}g||f.push("ref="+b);a.segment(f);return a}})});k.when("cr-A","jQuery","cr-log-utils","cr-string-utils","afterReady").register("cr-weblab-utils",function(b,a,c,d){function f(d,e,f,k){p[e]||(c.logCount(f,0,k),d=h(a(d),e,f,
k)(),m[e]=(m[e]||[]).concat(d),b.on.scroll(d))}function h(a,c,d,f){return function x(){b.inView(a)&&(e(c,d,f),b.each(m[c]||[],function(a){b.off("scroll",a)}));return x}}function e(a,d,e){p[a]||(p[a]=!0,b.post("/ss/customer-reviews/ajax/weblab-trigger",{params:{weblabId:a}}),c.logCount(d,1,e))}var p={},m={};b.each(a("*[data-cr-weblab-trigger-on-scroll]"),function(b,c){var e=a(b),h=e.attr("data-cr-weblab-trigger-on-scroll"),h=d.parseJSON(h);if(null!==h){var m="cr-weblab-trigger-on-scroll-"+c;e.addClass(m);
f("."+m,h.weblabId,h.metricName,h.prefix)}});return{triggerOnScrollIntoView:f,triggerWeblab:e}});k.when("A").register("histogram-trigger",function(b){function a(){b.onScreen(b.$("#histogramTable"))&&b.trigger("scroll")}b.on.afterLoad(a);return{triggerHistogram:a}})});
/* ******** */
(function(k){var n=window.AmazonUIPageJS||window.P,t=n._namespace||n.attributeErrors,b=t?t("CustomerReviewsMedleyAssets"):n;b.guardFatal?b.guardFatal(k)(b,window):b.execute(function(){k(b,window)})})(function(k,n,t){k.when("A","medley-view","medley-model","ready").register("medley-controller",function(b,a,c){function d(b){b=c.getASIN();var d=a.getDisplayedASIN();d&&b!==d&&(a.fadeReviews(!0),c.getReviews(d,function(){c.setASIN(d)},function(){},function(){a.fadeReviews(!1)}))}var f=a.getLoadedASIN();
c.setASIN(f);b.on("a:pageUpdate",d);return{onTwist:d}});k.when("A","jQuery").register("medley-view",function(b,a){return{getDisplayedASIN:function(){return String(a("#ASIN").val()||"")},getLoadedASIN:function(){return(b.$("#cr-state-object").data("state")||{}).asin||""},fadeReviews:function(b){!1===b?a("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",1):a("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",.5)}}});
k.when("A","cr-global-model","cr-ajax-model","cr-uri-utils").register("medley-model",function(b,a,c,d){function f(a){var b=d.getUrlParametersMap()||{};b.asin=a;return b}var h;return{setASIN:function(a){h=a||""},getASIN:function(){return h},getReviews:function(a,b,d,g){"string"===typeof a&&10===a.length?c.post("/ss/customer-reviews/ajax/medley-reviews/get/",{params:f(a),attribution:"getMedleyReviews",success:b,error:d,finallyCallback:g}):"function"===typeof g&&g()}}});k.when("A","review-skyfall-view",
"review-skyfall-model","reviews-constants","cr-global-view","a-button","cr-log-utils").register("review-skyfall-controller",function(b,a,c,d,f,h,e){function k(a){a=f.getReftag(a);c.clickMetric(a,function(){})}function m(b,d){a.showMoreFeedbackSection(b.$target.closest(".feedback-section"));var e=f.getReftag(b);c.clickMetric(e,function(a){d.disable()})}b.declarative(d.events.FEEDBACK_CLICK,"click",function(a){var b=h(".cr-feedback-helpful-yes, .cr-feedback-helpful-no");m(a,b)});b.declarative(d.events.CLIQUE_CLICK,
"click",k);b.on("a:expander:clique-ratings-read-more:toggle:expand",function(a){e.incrementCount("skyfallReadMore")});b.on("a:popover:show:skyfallWhatsThis",function(a){e.incrementCount("skyfallWhatsThis")});return{feedbackClick:m,cliqueClick:k}});k.when("A","cr-ajax-model","cr-global-model").register("review-skyfall-model",function(b,a,c){return{clickMetric:function(b,f){var h=c.generateUrl("/ss/customer-reviews/ajax/reftag-trigger",b);a.post(h,{params:{},success:f})}}});
k.when("A","reviews-constants").register("review-skyfall-view",function(b,a){return{showMoreFeedbackSection:function(b){b.find(".more-feedback-section").removeClass(a.aui.HIDDEN);b.find(".is-feature-helpful-row").addClass(a.aui.HIDDEN)}}})});
/* ******** */
(function(k){var n=window.AmazonUIPageJS||window.P,t=n._namespace||n.attributeErrors,b=t?t("CustomerReviewsVotingAssets"):n;b.guardFatal?b.guardFatal(k)(b,window):b.execute(function(){k(b,window)})})(function(k,n,t){k.when("A","vote-model","vote-view","a-modal").register("vote-controller",function(b,a,c,d){function f(a,b){h(a,b);c.showElementByCssSelector(a,b.inFlight)}function h(a,b){c.hideElementByCssSelector(a,b.hideVoteComponents);b.hideAbuseComponents&&c.hideElementByCssSelector(a,b.hideAbuseComponents)}
function e(e,k){k.isReportAbuse&&(e=b.$("#mobile-abuse-"+k.voteInstanceId),d.get(e).hide());f(e,k.cssSelectors);a.submitVote(k.ajaxUrl,k.voteValue,k.voteInstanceId,k.csrfT,k.voteDimension,function(a){if(!0===a){a=e;var b=k.cssSelectors;h(a,b);c.showElementByCssSelector(a,b.onSuccess)}else a=e,b=k.cssSelectors,h(a,b),c.showElementByCssSelector(a,b.onError)},function(){var a=e,b=k.cssSelectors;h(a,b);c.showElementByCssSelector(a,b.onError)})}b.declarative("reviews:vote-action","click",function(a){e(a.$target,
a.data);a.$event.preventDefault()});return{submitVote:e}});k.when("A","cr-ajax-model").register("vote-model",function(b,a){return{submitVote:function(b,d,f,h,e,k,m){a.post(b,{params:{voteInstanceId:f,voteValue:d,csrfT:h,voteDimension:e},attribution:"submitVote",success:k,error:m})}}});k.when("A").register("vote-view",function(b){function a(a,b){return a.closest(".cr-vote").find(b)}return{hideThankYouAlert:function(b){a(b,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(b){a(b,
".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(b){a(b,".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(b){a(b,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(b){a(b,".cr-vote-feedback").addClass("aok-hidden")},hideButtons:function(b){a(b,".cr-vote-buttons").addClass("aok-hidden")},hideElementByCssSelector:function(b,d){a(b,d).addClass("aok-hidden")},showElementByCssSelector:function(b,d){a(b,d).removeClass("aok-hidden")}}})});
/* ******** */
(function(k){var n=window.AmazonUIPageJS||window.P,t=n._namespace||n.attributeErrors,b=t?t("CustomerReviewsGalleryAssets"):n;b.guardFatal?b.guardFatal(k)(b,window):b.execute(function(){k(b,window)})})(function(k,n,t){k.when("A","load").register("review-image-asset-loader",function(b){var a=!1;b.ajax("/gp/customer-reviews/aj/private/reviewsGallery/get-image-gallery-assets",{method:"post",success:function(b){k.load.css(b.reviewsLightboxCSS);var d=document.createElement("script");d.type="text/javascript";
d.async=!0;d.setAttribute("crossorigin","anonymous");d.src=b.reviewsLightboxJS;document.getElementsByTagName("head")[0].appendChild(d);a=!0;k.register("review-image-assets-loaded",{})},error:function(){var a;a="/gp/customer-reviews/aj/metrics/log-values?noCache="+(new Date).getTime();a+="&SimpleStack:ReviewImageAssetLoaderFailure=1";n.Image&&((new Image).src=a)}});return{isLoaded:function(){return a}}});k.when("A","jQuery","cr-log-utils","reviews-constants","review-image-assets-loaded").register("review-image-binder",
function(b,a,c,d){function f(b,d,e,f,p){if(!(b&&d&&e instanceof a&&f instanceof a&&p instanceof a))return c.logError("Invalid parameters for imageBinder.initializeEventHandlers with ASIN: "+b+", galleryName: "+d+", $popoverTrigger: "+e+", $thumbnails: "+f+", $galleryLink: "+p,"FATAL"),!1;var n="reviewsLightbox-ready-"+d;f.click(function(){h(b,d);var c=f.index(this);e.click();k.when(n).execute(function(){a("#"+d).trigger("jumpToImageAtIndex",c)})});p.click(function(){h(b,d);e.click();k.when(n).execute(function(){a("#"+
d).trigger("hideImmersiveView")})});return!0}function h(a,b){if(!a||!b)return c.logError("Invalid parameters for imageBinder.initializeImageGallery with ASIN: "+a+", galleryName: "+b,"FATAL"),!1;if(e)return!0;(new ReviewsLightbox(b,"DESKTOP")).initializeForAsin(a);return e=!0}var e=!1,p={};k.when("reviewsLightbox-js").execute(function(){var b=a("#reviews-image-gallery-container"),c=b.attr("data-asin");0<b.length&&c&&f(c,"reviews-image-gallery",b.find(".a-popover-trigger"),b.find(".review-image-tile"),
b.find("#reviews-image-gallery-link"))});b.on(d.events.RELOAD_COMPLETE,function(){p={}});return{bindReview:function(b,c,d){var e=new ReviewGallery(d,"DESKTOP"),f=a("#"+c);f.find(".review-image-tile").each(function(c){a(this).click(function(){p[b]||(e.initializeForReview(b),p[b]=!0);f.find(".a-popover-trigger").click();k.when("reviewsLightbox-ready-"+d).execute(function(){e.render();e.showImageAtIndex(c)})})})},initializeImageGallery:h,initializeEventHandlers:f}});k.when("A","jQuery",
"cr-video-model","cr-video-view","reviews-constants").register("cr-video-controller",function(b,a,c,d,f){function h(){b.each(a(".review-views .review"),function(a,b){if(a&&a.id){var f=c.getEmbedInfo(a.id);f&&d.embedVideo(f)}})}b.on(f.events.RELOAD_COMPLETE,function(){h()});h();return{initAll:h}});k.when("jQuery").register("cr-video-model",function(b){return{getEmbedInfo:function(a){var c="video-block-"+a,d=b("#"+a+" .video-url").val(),f=b("#"+a+" .video-slate-img-url").val(),h=b("#cr-video-swf-url").val();
return a&&d&&h?{videoDomId:c,videoUrl:d,videoSlateImgUrl:f,videoSwfUrl:h}:!1}}});k.when("jQuery","afterLoad").register("cr-video-view",function(b){k.now("Airy").execute(function(a){var c=b("#cr-airy-js-source-url").val(),d=b("#cr-airy-css-source-url").val();a||"string"!==typeof c||"string"!==typeof d||(k.load.js(c),k.load.css(d))});return{embedVideo:function(a){k.when("Airy").execute(function(b){b.embed({parentId:a.videoDomId,streamingUrls:[a.videoUrl],slateImages:{preloadSlate:a.videoSlateImgUrl},
swfUrl:a.videoSwfUrl,desiredMode:"html"})})}}})});
/* ******** */
(function(k){var n=window.AmazonUIPageJS||window.P,t=n._namespace||n.attributeErrors,b=t?t("CustomerReviewsFilteringAssets"):n;b.guardFatal?b.guardFatal(k)(b,window):b.execute(function(){k(b,window)})})(function(k,n,t){k.when("cr-A","jQuery","cr-filtering-view","cr-filtering-model","cr-global-view","reviews-constants","cr-streaming-utils","cr-log-utils").register("cr-filtering-controller",function(b,a,c,d,f,h,e,p){function m(a){var b=!1,c=!1;a.toggleFilters&&(c=!0);b=d.setReviewerType(a.reviewerType,
c)||b;b=d.setFormatType(a.formatType,c)||b;b=d.setFilterByKeyword(a.filterByKeyword,c)||b;b=d.setSortOrder(a.sortOrder,c)||b;b=d.setStarFilter(a.filterByStar,c)||b;return b=d.setPageNumber(a.pageNumber,c)||b}function g(a){var g=!1;a&&a.data&&(g=m(a.data))&&(c.hideReviewLoadError(),c.hideReviews(),c.showLoadingSpinner(),b.trigger(h.events.FILTER_APPLY_BEGIN,a),d.getReviews(function(){c.showReviews();b.trigger(h.events.FILTER_APPLY_SUCCESS,a)},function(){c.showReviewLoadError();b.trigger(h.events.FILTER_APPLY_ERROR,
a)},function(){c.hideLoadingSpinner();b.trigger(h.events.FILTER_APPLY_DONE,a);b.trigger(h.events.RELOAD_COMPLETE)},function(a){"appendFadeIn"===a[0]&&e.appendFadeIn(a)},f.getReftag(a)),a.data.scrollToSelector&&f.scrollTo(a.data.scrollToSelector,0))}a=c.getLoadedASIN();d.setASIN(a);d.setReviewsAjaxUrl(c.getReviewsAjaxUrl());b.declarative(h.events.FILTER_APPLY,"click",b.compositeEventWrapper(g,!0,100));return{setFilterParams:m,onFilterApply:g}});k.when("A","cr-ajax-model","ready").register("cr-filtering-model",
function(b,a){function c(){return e.asin||""}function d(){return p||""}function f(a,b){b?e[a]=b:delete e[a]}function h(a,b,c){var d=!1;a&&b!==t&&(d=(e[a]||"")!==b,!d&&c&&(b="",d=!0),f(a,b));return d}var e={},p="",m;return{getReviews:function(b,c,d,f,h){var k=p;m&&a.abort(m);h&&(k+="ref="+h);m=a.post(k,{params:e,attribution:"getFilteredReviews",success:b,error:c,finallyCallback:function(){d();m=0},chunk:f})},setASIN:function(a){var b=c()!==a;f("asin",a);return b},getASIN:c,setReviewsAjaxUrl:function(a){var b=
d()!==a;p=a||"";return b},getReviewsAjaxUrl:d,setReviewerType:function(a,b){return h("reviewerType",a,b)},getReviewerType:function(){return e.reviewerType||""},setFormatType:function(a,b){return h("formatType",a,b)},getFormatType:function(){return e.formatType||""},setFilterByKeyword:function(a,b){return h("filterByKeyword",a,b)},getFilterByKeyword:function(){return e.filterByKeyword||""},setSortOrder:function(a,b){return h("sortBy",a,b)},getSortOrder:function(){return e.sortBy||""},setStarFilter:function(a,
b){return h("filterByStar",a,b)},getStarFilter:function(){return e.filterByStar||""},setPageNumber:function(a,b){return h("pageNumber",a,b)},getPageNumber:function(){return e.pageNumber||""},getFilterParams:function(){return e||{}},updateFilterParam:f}});k.when("A","jQuery","ready").register("cr-filtering-view",function(b,a){return{getLoadedASIN:function(){return(a("#cr-state-object").data("state")||{}).asin||""},getReviewsAjaxUrl:function(){return(a("#cr-state-object").data("state")||
{}).reviewsAjaxUrl||""},showLoadingSpinner:function(){a(".cr-reviews-loading").removeClass("aok-hidden")},hideLoadingSpinner:function(){a(".cr-reviews-loading").addClass("aok-hidden")},hideReviews:function(){a(".filterable-reviews-content").addClass("aok-hidden")},showReviews:function(){a(".filterable-reviews-content").removeClass("aok-hidden")},showReviewLoadError:function(){a(".review-load-error").removeClass("aok-hidden")},hideReviewLoadError:function(){a(".review-load-error").addClass("aok-hidden")}}});
k.when("cr-A","cr-lighthut-terms-view","reviews-constants","cr-log-utils").register("cr-lighthut-terms-controller",function(b,a,c,d){function f(b){b&&b.filterByKeyword!==t&&(a.setSelected(b.filterByKeyword),d.incrementCount("LighthutTermClicked"))}b.on(c.events.FILTER_APPLY_BEGIN,b.compositeEventWrapper(function(a){a&&a.data&&f(a.data)}));return{onFilterApplied:f}});k.when("A","jQuery","ready").register("cr-lighthut-terms-view",function(b,a){return{setSelected:function(b){var d=
(b=a("#cr-lighthouse-term-"+b))&&b.hasClass("cr-lighthut-term-selected");a(".cr-lighthut-term-selected").removeClass("cr-lighthut-term-selected");d||b.addClass("cr-lighthut-term-selected")}}})});
/* ******** */
